export type AcademicEvent = {
  id: string;
  date: string;
  title: string;
  place: string;
  city: string;
  country: "VN" | "RU" | "ONLINE";
  format: "IN_PERSON" | "HYBRID" | "ONLINE";
  organizer: string;
  topics: string[];
  state: "OPEN" | "PLANNED" | "COMPLETED" | "CLOSED";
  action: string;
  description: string;
  attendeesCount: number;
  registrationDeadline?: string;
};

export const DEMO_ACADEMIC_EVENTS: AcademicEvent[] = [
  {
    id: "ac01",
    date: "05–09/09/2026",
    title: "Hội thảo Khoa học Vật liệu Biển Song phương Việt – Nga lần thứ 8",
    place: "Viện Hải dương học · Nha Trang",
    city: "Nha Trang",
    country: "VN",
    format: "HYBRID",
    organizer: "VAST ↔ FEB RAS",
    topics: ["Vật liệu mới", "Chống ăn mòn", "Vật liệu sinh học"],
    state: "OPEN",
    action: "Đăng ký tham gia",
    description: "Diễn đàn trao đổi kết quả nghiên cứu mới nhất về độ bền vật liệu trong môi trường biển nhiệt đới và hàn đới.",
    attendeesCount: 120,
    registrationDeadline: "31/08/2026",
  },
  {
    id: "ac02",
    date: "18/10/2026",
    title: "Seminar Quốc tế FEB RAS: Sinh học Biển Sâu và Hoạt chất Tự nhiên",
    place: "Trụ sở FEB RAS · Vladivostok",
    city: "Vladivostok",
    country: "RU",
    format: "ONLINE",
    organizer: "FEB RAS & PIBOC",
    topics: ["Sinh học biển", "Hợp chất tự nhiên", "Hóa sinh"],
    state: "OPEN",
    action: "Đăng ký tham gia",
    description: "Báo cáo chuyên đề về cấu trúc phân tử và tiềm năng dược lý của các hợp chất chiết xuất từ sinh vật đáy biển sâu.",
    attendeesCount: 85,
    registrationDeadline: "10/10/2026",
  },
  {
    id: "ac03",
    date: "11–20/11/2026",
    title: "Chương trình Trao đổi Chuyên gia Vật liệu và Cảm biến Nano",
    place: "MISIS · Moskva",
    city: "Moskva",
    country: "RU",
    format: "IN_PERSON",
    organizer: "MISIS ↔ VAST",
    topics: ["Vật liệu nano", "Cảm biến", "Điện hóa học"],
    state: "PLANNED",
    action: "Theo dõi lịch trình",
    description: "Khóa thực hành đo kiểm phổ bề mặt nâng cao dành cho các nhà nghiên cứu trẻ hai nước.",
    attendeesCount: 30,
    registrationDeadline: "15/10/2026",
  },
  {
    id: "ac04",
    date: "15/08/2026",
    title: "Tọa đàm Dữ liệu Hải dương học Mở và Chuẩn hóa Siêu dữ liệu",
    place: "Trực tuyến qua VN–RU Network Portal",
    city: "Online",
    country: "ONLINE",
    format: "ONLINE",
    organizer: "VNU & FEB RAS Data Center",
    topics: ["Dữ liệu khoa học", "Chuẩn hóa FAIR", "Hải dương học"],
    state: "COMPLETED",
    action: "Xem tài liệu hội thảo",
    description: "Tổng kết kinh nghiệm triển khai khung siêu dữ liệu NetCDF và API liên thông dữ liệu quan trắc biển.",
    attendeesCount: 150,
  },
  {
    id: "ac05",
    date: "22–24/09/2026",
    title: "Hội nghị Toàn thể Ban Chỉ đạo Hợp tác KH & CN Liên Chính phủ",
    place: "Hà Nội · Khách sạn Melia",
    city: "Hà Nội",
    country: "VN",
    format: "IN_PERSON",
    organizer: "Ủy ban Hợp tác KH & CN Việt – Nga",
    topics: ["Chiến lược KH & CN", "Chính sách song phương", "Tổng kết hợp tác"],
    state: "PLANNED",
    action: "Theo dõi thông cáo",
    description: "Phiên họp thường niên rà soát các chương trình nghiên cứu trọng điểm giai đoạn 2026–2030.",
    attendeesCount: 200,
  },
  {
    id: "ac06",
    date: "02/10/2026",
    title: "Workshop Chuyên đề: AI trong Dự báo Sạt lở và Tai biến Bờ biển",
    place: "ĐHQG Hà Nội (VNU-HN)",
    city: "Hà Nội",
    country: "VN",
    format: "HYBRID",
    organizer: "VNU ↔ MISIS",
    topics: ["AI & Địa chất", "Địa mạo ven biển", "Cảnh báo sớm"],
    state: "OPEN",
    action: "Đăng ký tham gia",
    description: "Trình diễn các mô hình học sâu và hệ thống cảnh báo sớm sạt lở ven bờ áp dụng cho dải ven biển miền Trung.",
    attendeesCount: 95,
    registrationDeadline: "25/09/2026",
  },
  {
    id: "ac07",
    date: "14/11/2026",
    title: "Seminar Kỹ thuật: Thiết bị Tự hành Dưới nước AUV trong Khảo sát Biển",
    place: "SPbPU · St. Petersburg",
    city: "St. Petersburg",
    country: "RU",
    format: "HYBRID",
    organizer: "SPbPU ↔ HUST",
    topics: ["Robot biển", "Cơ điện tử", "Thủy âm"],
    state: "PLANNED",
    action: "Đăng ký nhận tài liệu",
    description: "Giới thiệu các giải pháp định vị thủy âm và thuật toán bám quỹ đạo tự hành trong vùng nước nông nhiệt đới.",
    attendeesCount: 70,
    registrationDeadline: "01/11/2026",
  },
  {
    id: "ac08",
    date: "08/12/2026",
    title: "Hội thảo Trực tuyến: Chuyển đổi Năng lượng Sóng và Dòng chảy Ven biển",
    place: "Đại học Bách Khoa TP.HCM (HCMUT)",
    city: "TP. Hồ Chí Minh",
    country: "VN",
    format: "ONLINE",
    organizer: "HCMUT ↔ FEFU",
    topics: ["Năng lượng biển", "Tối ưu hóa năng lượng", "Công trình thủy"],
    state: "OPEN",
    action: "Đăng ký tham gia",
    description: "Đánh giá tiềm năng khai thác năng lượng sóng quy mô trạm quan trắc ven hải đảo.",
    attendeesCount: 65,
    registrationDeadline: "01/12/2026",
  },
  {
    id: "ac09",
    date: "20/07/2026",
    title: "Khóa tập huấn Xử lý Dữ liệu Viễn thám và Trắc đạc Địa hình Đáy biển",
    place: "MSU · Moskva & Trực tuyến",
    city: "Moskva",
    country: "RU",
    format: "HYBRID",
    organizer: "MSU Faculty of Geography",
    topics: ["Địa mạo ven biển", "Viễn thám", "Mô hình hóa số"],
    state: "COMPLETED",
    action: "Xem video bài giảng",
    description: "Hướng dẫn xây dựng mô hình số độ cao đáy biển từ dữ liệu sonar quét sườn kết hợp ảnh vệ tinh Sentinel.",
    attendeesCount: 110,
  },
  {
    id: "ac10",
    date: "12/06/2026",
    title: "Báo cáo Khoa học: Khảo sát Địa chất Khoáng sản Biển Sâu Tây Thái Bình Dương",
    place: "GEOKHI RAS · Moskva",
    city: "Moskva",
    country: "RU",
    format: "IN_PERSON",
    organizer: "GEOKHI RAS ↔ VIGMR",
    topics: ["Địa chất biển", "Địa hóa học", "Khoáng sản"],
    state: "COMPLETED",
    action: "Tải báo cáo tóm tắt",
    description: "Trình bày kết quả phân tích đồng vị kết hạch sắt-mangan thu thập trong chuyến khảo sát liên hợp 2025.",
    attendeesCount: 45,
  },
  {
    id: "ac11",
    date: "19/01/2027",
    title: "Hội nghị Quốc tế: Quy hoạch Đô thị Ven biển Thích ứng Rủi ro Biến đổi Khí hậu",
    place: "Đại học Kinh tế Quốc dân (NEU) · Hà Nội",
    city: "Hà Nội",
    country: "VN",
    format: "HYBRID",
    organizer: "NEU & HSE University",
    topics: ["Khí hậu", "Đô thị ven biển", "Phân tích không gian"],
    state: "PLANNED",
    action: "Gửi tóm tắt báo cáo",
    description: "Chia sẻ kinh nghiệm quốc tế và đề xuất giải pháp chính sách công trình mềm thích ứng triều cường dâng cao.",
    attendeesCount: 140,
    registrationDeadline: "15/12/2026",
  },
  {
    id: "ac12",
    date: "10/02/2027",
    title: "Diễn đàn Công nghệ Lượng tử và Ứng dụng Cảm biến Địa vật lý",
    place: "Viện Hàn lâm KH & CN Việt Nam (VAST)",
    city: "Hà Nội",
    country: "VN",
    format: "IN_PERSON",
    organizer: "VAST ↔ MISIS",
    topics: ["Cảm biến lượng tử", "Từ kế", "Địa vật lý"],
    state: "PLANNED",
    action: "Đăng ký tham gia",
    description: "Giới thiệu tiến bộ mới trong kỹ thuật từ kế nguyên tử quang học ứng dụng cho khảo sát địa chấn và khoáng sản đáy.",
    attendeesCount: 80,
    registrationDeadline: "20/01/2027",
  },
  {
    id: "ac13",
    date: "25/03/2027",
    title: "Hội thảo Thường niên: Công nghệ Sinh học và Hoạt chất Biển Tiên tiến",
    place: "Viện VKIST · Khu CNC Hòa Lạc",
    city: "Hà Nội",
    country: "VN",
    format: "IN_PERSON",
    organizer: "VKIST ↔ PIBOC FEB RAS",
    topics: ["Công nghệ sinh học", "Hóa sinh", "Dược liệu biển"],
    state: "PLANNED",
    action: "Theo dõi thông tin",
    description: "Đánh giá các quy trình chiết xuất xanh và bảo quản hoạt tính sinh học từ sinh vật biển nhiệt đới.",
    attendeesCount: 90,
    registrationDeadline: "10/03/2027",
  },
  {
    id: "ac14",
    date: "15/05/2026",
    title: "Seminar Bàn tròn: Chiến lược Phát triển Năng lượng Hydro Xanh từ Nước biển",
    place: "Trực tuyến",
    city: "Online",
    country: "ONLINE",
    format: "ONLINE",
    organizer: "VAST & MISIS Clean Energy Lab",
    topics: ["Hydro xanh", "Xúc tác điện hóa", "Vật liệu mới"],
    state: "COMPLETED",
    action: "Xem bản ghi",
    description: "Thảo luận các rào cản kỹ thuật chính trong phản ứng oxy hóa clo và thiết kế điện cực màng bảo vệ.",
    attendeesCount: 130,
  },
];

export function getAcademicEventById(id: string): AcademicEvent | undefined {
  return DEMO_ACADEMIC_EVENTS.find((event) => event.id === id);
}

export function getAcademicEventsByState(state: AcademicEvent["state"]): AcademicEvent[] {
  return DEMO_ACADEMIC_EVENTS.filter((event) => event.state === state);
}
