import type { OrganizationEndorsement } from "../demo-v2/types";

export const DEMO_ENDORSEMENTS: OrganizationEndorsement[] = [
  {
    id: "en01",
    proposalId: "p11",
    code: "RU-VN-2026-CLIMATE-11",
    title: "Đánh giá rủi ro khí hậu cho đô thị ven biển",
    lead: "TS Nguyễn Thảo",
    partnerOrg: "HSE",
    facilities: "Phòng thí nghiệm GIS kinh tế lượng, kho dữ liệu khí hậu lịch sử và nhóm chuyên gia mô hình hóa không gian.",
    state: "PENDING",
    deadline: "01/09/2026",
  },
  {
    id: "en02",
    proposalId: "p02",
    code: "RU-VN-2026-AI-04",
    title: "AI dự báo sớm tai biến địa chất ven biển",
    lead: "TS Nguyễn Minh Anh",
    partnerOrg: "MISIS",
    facilities: "Cụm máy chủ tính toán GPU hiệu năng cao và kho dữ liệu khảo sát địa chất ven bờ.",
    state: "NEEDS_INFO",
    deadline: "25/08/2026",
  },
  {
    id: "en03",
    proposalId: "p03",
    code: "RU-VN-2026-MAR-02",
    title: "Giám sát đa dạng sinh học biển bằng dữ liệu ảnh",
    lead: "TS Trần Hải",
    partnerOrg: "POI RAS",
    facilities: "Hệ thống camera lặn khảo sát đáy biển và trạm nghiên cứu ven bờ Hòn Mun.",
    state: "ENDORSED",
    deadline: "18/08/2026",
  },
  {
    id: "en04",
    proposalId: "p05",
    code: "RU-VN-2026-ROBOT-05",
    title: "Robot tự hành khảo sát vùng nước nông",
    lead: "TS Đặng Quốc",
    partnerOrg: "SPbPU",
    facilities: "Bể thử thủy lực mini và xưởng gia công cơ điện tử chính xác.",
    state: "DECLINED",
    deadline: "19/08/2026",
  },
  {
    id: "en05",
    proposalId: "p01",
    code: "RU-VN-2026-NANO-01",
    title: "Vật liệu nano-composite chịu ăn mòn biển nhiệt đới",
    lead: "PGS.TS Lê Thị Mai",
    partnerOrg: "FEB RAS",
    facilities: "Phòng đo kiểm phân tích bề mặt nano và buồng thử nghiệm ăn mòn gia tốc muối biển.",
    state: "PENDING",
    deadline: "30/08/2026",
  },
  {
    id: "en06",
    proposalId: "p04",
    code: "RU-VN-2026-DATA-03",
    title: "Liên thông dữ liệu quan trắc hải dương VN–RU",
    lead: "PGS.TS Phạm Sơn",
    partnerOrg: "FEB RAS",
    facilities: "Trung tâm máy chủ lưu trữ dữ liệu khoa học VNU và đường truyền chuyên dụng.",
    state: "ENDORSED",
    deadline: "02/09/2026",
  },
  {
    id: "en07",
    proposalId: "p06",
    code: "RU-VN-2026-COAST-06",
    title: "Mô hình số biến động đường bờ khu vực nhiệt đới",
    lead: "TS Bùi Thu",
    partnerOrg: "MSU",
    facilities: "Phòng thí nghiệm địa lý biển và trạm đo trắc đạc bờ biển miền Trung.",
    state: "ENDORSED",
    deadline: "05/09/2026",
  },
  {
    id: "en08",
    proposalId: "p07",
    code: "RU-VN-2026-BIO-08",
    title: "Độ bền vật liệu sinh học trong điều kiện biển",
    lead: "PGS.TS Lê Thị Mai",
    partnerOrg: "FEB RAS",
    facilities: "Buồng thử nghiệm gia tốc môi trường biển và thiết bị phân tích phổ XPS.",
    state: "ENDORSED",
    deadline: "30/08/2026",
  },
  {
    id: "en09",
    proposalId: "p08",
    code: "RU-VN-2026-ENERGY-09",
    title: "Tối ưu vật liệu cho năng lượng sóng quy mô nhỏ",
    lead: "TS Vũ Linh",
    partnerOrg: "FEFU",
    facilities: "Kênh tạo sóng nhân tạo và thiết bị đo kiểm thủy khí động lực HCMUT.",
    state: "NEEDS_INFO",
    deadline: "28/08/2026",
  },
  {
    id: "en10",
    proposalId: "p09",
    code: "RU-VN-2025-OCEAN-03",
    title: "Đồng bộ chuỗi quan trắc hải dương học ven bờ",
    lead: "TS Đỗ Hùng",
    partnerOrg: "FEB RAS",
    facilities: "Trạm quan trắc phao ngầm ven bờ và tàu nghiên cứu biển IO VAST.",
    state: "ENDORSED",
    deadline: "15/12/2025",
  },
  {
    id: "en11",
    proposalId: "p10",
    code: "RU-VN-2026-SENSOR-10",
    title: "Cảm biến hóa học bền môi trường nước mặn",
    lead: "TS Lương Hà",
    partnerOrg: "MISIS",
    facilities: "Phòng thí nghiệm cảm biến hóa sinh và máy đo điện hóa phân giải cao.",
    state: "DECLINED",
    deadline: "12/08/2026",
  },
  {
    id: "en12",
    proposalId: "p12",
    code: "RU-VN-2026-GEO-12",
    title: "Cơ sở dữ liệu địa chất biển song phương",
    lead: "TS Hoàng Long",
    partnerOrg: "GEOKHI RAS",
    facilities: "Thiết bị đo địa chấn nông và phòng phân tích thạch học VIGMR.",
    state: "DECLINED",
    deadline: "10/09/2026",
  },
  {
    id: "en13",
    proposalId: "p16",
    code: "RU-VN-2026-CYBER-16",
    title: "Mã hóa nhẹ và xác thực dữ liệu cho mạng phao quan trắc",
    lead: "PGS.TS Phạm Sơn",
    partnerOrg: "SPbPU",
    facilities: "Phòng lab an ninh mạng và hạ tầng kiểm thử giao thức IoT.",
    state: "PENDING",
    deadline: "22/11/2026",
  },
  {
    id: "en14",
    proposalId: "p17",
    code: "RU-VN-2026-AGRI-17",
    title: "Chỉ thị phân tử sàng lọc giống lúa chịu mặn ven biển",
    lead: "TS Vũ Kim Dung",
    partnerOrg: "FEB RAS",
    facilities: "Hệ thống máy giải trình tự gen NGS và nhà màng khảo nghiệm chịu mặn.",
    state: "PENDING",
    deadline: "14/12/2026",
  },
  {
    id: "en15",
    proposalId: "p18",
    code: "RU-VN-2026-CORAL-18",
    title: "Nhận dạng tự động biến động rạn san hô bằng AI và camera đáy",
    lead: "TS Trần Hải",
    partnerOrg: "POI RAS",
    facilities: "Trung tâm ảnh sinh thái biển và phòng xử lý đồ họa GPU.",
    state: "NEEDS_INFO",
    deadline: "25/08/2026",
  },
  {
    id: "en16",
    proposalId: "p19",
    code: "RU-VN-2026-QUANTUM-19",
    title: "Từ kế lượng tử quang học thăm dò khoáng sản tầng nông",
    lead: "GS.TS Trần Đình Nam",
    partnerOrg: "MISIS",
    facilities: "Phòng thí nghiệm quang lượng tử và buồng khử từ VAST.",
    state: "ENDORSED",
    deadline: "30/11/2026",
  },
  {
    id: "en17",
    proposalId: "p20",
    code: "RU-VN-2026-SEDIMENT-20",
    title: "Phân tích địa hóa đồng vị trầm tích bồi tụ cửa sông",
    lead: "TS Hoàng Long",
    partnerOrg: "GEOKHI RAS",
    facilities: "Phòng chuẩn bị mẫu địa chất và máy đo phổ gamma.",
    state: "ENDORSED",
    deadline: "15/09/2026",
  },
  {
    id: "en18",
    proposalId: "p21",
    code: "RU-VN-2025-EDDY-21",
    title: "Cấu trúc vi mô và năng lượng xoáy nhiệt đới Tây Thái Bình Dương",
    lead: "TS Đỗ Hùng",
    partnerOrg: "FEB RAS",
    facilities: "Tàu nghiên cứu khoa học biển và trạm đo hải văn Nha Trang.",
    state: "ENDORSED",
    deadline: "30/11/2025",
  },
];

export function getEndorsementById(id: string): OrganizationEndorsement | undefined {
  return DEMO_ENDORSEMENTS.find((item) => item.id === id || item.code === id);
}

export function getEndorsementByProposalId(proposalId: string): OrganizationEndorsement | undefined {
  return DEMO_ENDORSEMENTS.find((item) => item.proposalId === proposalId);
}
