export type Expert = {
  id: string;
  initials: string;
  name: string;
  degree: string;
  roleTitle: string;
  institution: string;
  institutionId: string;
  country: "VN" | "RU";
  city: string;
  topics: string[];
  publications: string[];
  hIndex: number;
  activeProjectsCount: number;
  email: string;
  bio: string;
};

export const DEMO_EXPERTS: Expert[] = [
  {
    id: "exp-vn-01",
    initials: "LM",
    name: "PGS.TS Lê Thị Mai",
    degree: "Phó Giáo sư, Tiến sĩ",
    roleTitle: "Trưởng phòng Vật liệu Sinh học & Bề mặt",
    institution: "Viện Hàn lâm Khoa học và Công nghệ Việt Nam (VAST)",
    institutionId: "org-vn-01",
    country: "VN",
    city: "Hà Nội",
    topics: ["Vật liệu mới", "Vật liệu sinh học", "Chống ăn mòn nhiệt đới"],
    publications: [
      "Degradation and anti-corrosion properties of bio-composites in tropical seawater (2025)",
      "Surface modification of silica nano-coatings for marine durability (2024)",
      "Bilateral assessment of tropical marine bio-fouling dynamics (2023)",
    ],
    hIndex: 24,
    activeProjectsCount: 2,
    email: "mai.le@vast.gov.vn",
    bio: "Chuyên gia đầu ngành về vật liệu nano-composite và giải pháp bảo vệ công trình trong môi trường biển nhiệt đới.",
  },
  {
    id: "exp-ru-01",
    initials: "EK",
    name: "Prof. Elena Kurchatova",
    degree: "Doctor of Sciences, Professor",
    roleTitle: "Head of Functional Nanomaterials Laboratory",
    institution: "National University of Science and Technology MISIS",
    institutionId: "org-ru-02",
    country: "RU",
    city: "Moskva",
    topics: ["Vật liệu nano", "Bề mặt chức năng", "Lưu trữ năng lượng"],
    publications: [
      "Nanostructured hybrid materials under extreme thermal and mechanical loads (2025)",
      "Electrochemical impedance spectroscopy of modified alloys (2024)",
      "Joint Russian-Vietnamese characterization of marine alloys (2023)",
    ],
    hIndex: 32,
    activeProjectsCount: 3,
    email: "kurchatova@misis.ru",
    bio: "Chuyên gia về cấu trúc nano, vật liệu lai hợp kim và bề mặt chức năng phục vụ điều kiện khắc nghiệt.",
  },
  {
    id: "exp-vn-02",
    initials: "NA",
    name: "TS Nguyễn Minh Anh",
    degree: "Tiến sĩ Kỹ thuật",
    roleTitle: "Chuyên viên nghiên cứu cao cấp",
    institution: "Viện Hàn lâm Khoa học và Công nghệ Việt Nam (VAST)",
    institutionId: "org-vn-01",
    country: "VN",
    city: "Hà Nội",
    topics: ["AI & Địa chất", "Quan trắc sạt lở", "Viễn thám"],
    publications: [
      "Deep neural networks for coastal disaster early warning (2026)",
      "Multi-temporal satellite radar interferometry for subsidence tracking (2024)",
    ],
    hIndex: 18,
    activeProjectsCount: 1,
    email: "minhanh.nguyen@vast.gov.vn",
    bio: "Nghiên cứu ứng dụng trí tuệ nhân tạo và dữ liệu viễn thám trong cảnh báo sớm rủi ro sạt lở ven bờ.",
  },
  {
    id: "exp-ru-02",
    initials: "IM",
    name: "Dr. Ivan Morozov",
    degree: "Candidate of Technical Sciences",
    roleTitle: "Senior Researcher in Geo-Informatics",
    institution: "National University of Science and Technology MISIS",
    institutionId: "org-ru-02",
    country: "RU",
    city: "Moskva",
    topics: ["AI & Địa chất", "Địa tin học", "Mô hình hóa số"],
    publications: [
      "Spatiotemporal graph networks for landslide hazard forecasting (2025)",
      "High-performance numerical simulation of geological instability (2024)",
    ],
    hIndex: 21,
    activeProjectsCount: 2,
    email: "morozov.i@misis.ru",
    bio: "Chuyên sâu về mô hình đồ thị không gian-thời gian và mô phỏng số biến động địa chất.",
  },
  {
    id: "exp-vn-03",
    initials: "TH",
    name: "TS Trần Hải",
    degree: "Tiến sĩ Sinh học Biển",
    roleTitle: "Trưởng phòng Đa dạng Sinh học Đáy Biển",
    institution: "Viện Hải dương học (IO VAST)",
    institutionId: "org-vn-02",
    country: "VN",
    city: "Nha Trang",
    topics: ["Sinh học biển", "Phân loại học hình ảnh", "Đa dạng sinh học"],
    publications: [
      "Benthic coral reef biodiversity assessment via deep underwater imaging (2025)",
      "Taxonomic revision of deep-sea invertebrates in the Western Pacific (2023)",
    ],
    hIndex: 19,
    activeProjectsCount: 2,
    email: "hai.tran@vnio.vast.vn",
    bio: "Chủ nhiệm nhiều đợt khảo sát đa dạng sinh học biển sâu và phân loại sinh vật đáy bằng thị giác máy tính.",
  },
  {
    id: "exp-ru-03",
    initials: "AV",
    name: "Dr. Anna Volkova",
    degree: "Candidate of Biological Sciences",
    roleTitle: "Principal Investigator in Marine Ecology",
    institution: "V.I. Il'ichev Pacific Oceanological Institute (POI RAS)",
    institutionId: "org-ru-03",
    country: "RU",
    city: "Vladivostok",
    topics: ["Sinh thái biển", "Vi sinh vật biển", "Đa dạng sinh học"],
    publications: [
      "Microbial communities in marginal sea sediments (2025)",
      "Bilateral atlas of tropical-subtropical transitional marine fauna (2024)",
    ],
    hIndex: 22,
    activeProjectsCount: 1,
    email: "volkova@poi.dvo.ru",
    bio: "Nghiên cứu cấu trúc quần xã vi sinh vật trầm tích và biến động hệ sinh thái biển khu vực Đông Á.",
  },
  {
    id: "exp-vn-04",
    initials: "PS",
    name: "PGS.TS Phạm Sơn",
    degree: "Phó Giáo sư, Tiến sĩ",
    roleTitle: "Trưởng khoa Khoa học Dữ liệu",
    institution: "Đại học Quốc gia Hà Nội (VNU-HN)",
    institutionId: "org-vn-03",
    country: "VN",
    city: "Hà Nội",
    topics: ["Dữ liệu khoa học", "Hạ tầng phân tán", "Chuẩn hóa dữ liệu"],
    publications: [
      "Federated scientific data pipelines for bilateral oceanographic surveys (2025)",
      "Metadata schema interoperability across Asian and European repositories (2024)",
    ],
    hIndex: 27,
    activeProjectsCount: 2,
    email: "son.pham@vnu.edu.vn",
    bio: "Chuyên gia về hạ tầng dữ liệu mở, kiến trúc liên thông kho lưu trữ và quy chuẩn FAIR cho dữ liệu khoa học.",
  },
  {
    id: "exp-ru-04",
    initials: "PS",
    name: "Dr. Pavel Sidorov",
    degree: "Candidate of Phys-Math Sciences",
    roleTitle: "Head of Oceanographic Data Center",
    institution: "Far Eastern Branch of the Russian Academy of Sciences (FEB RAS)",
    institutionId: "org-ru-01",
    country: "RU",
    city: "Vladivostok",
    topics: ["Hải dương học", "Dữ liệu quan trắc", "Phân tích chuỗi thời gian"],
    publications: [
      "Quality control algorithms for long-term oceanographic time series (2025)",
      "Bilateral data exchange platform for Pacific and South China Sea data (2024)",
    ],
    hIndex: 23,
    activeProjectsCount: 1,
    email: "sidorov@dvo.ru",
    bio: "Phụ trách trung tâm dữ liệu hải dương học Viễn Đông, chuyên sâu về kiểm soát chất lượng dữ liệu quan trắc dài hạn.",
  },
  {
    id: "exp-vn-05",
    initials: "DQ",
    name: "TS Đặng Quốc",
    degree: "Tiến sĩ Cơ điện tử & Điều khiển",
    roleTitle: "Trưởng nhóm Robot Biển & Hệ thống Tự hành",
    institution: "Đại học Bách Khoa Hà Nội (HUST)",
    institutionId: "org-vn-04",
    country: "VN",
    city: "Hà Nội",
    topics: ["Robot biển", "Thiết bị tự hành", "Điều khiển thích nghi"],
    publications: [
      "Autonomous trajectory tracking for shallow-water inspection AUVs (2026)",
      "Hydrodynamic parameter estimation for underwater robotic platforms (2024)",
    ],
    hIndex: 16,
    activeProjectsCount: 1,
    email: "quoc.dang@hust.edu.vn",
    bio: "Chế tạo robot lặn khảo sát vùng nước nông và thuật toán điều khiển thích nghi trong dòng chảy ngầm.",
  },
  {
    id: "exp-ru-05",
    initials: "AP",
    name: "Prof. Alexei Petrov",
    degree: "Doctor of Technical Sciences, Professor",
    roleTitle: "Director of Robotics and Mechatronics Institute",
    institution: "Peter the Great St. Petersburg Polytechnic University (SPbPU)",
    institutionId: "org-ru-04",
    country: "RU",
    city: "St. Petersburg",
    topics: ["Robot tự hành", "Cơ điện tử biển", "Mô phỏng thủy động lực"],
    publications: [
      "Modular autonomous underwater vehicles for environmental monitoring (2025)",
      "Acoustic positioning and swarm navigation in coastal zones (2023)",
    ],
    hIndex: 35,
    activeProjectsCount: 3,
    email: "petrov@spbstu.ru",
    bio: "Chuyên gia hàng đầu về nền tảng robot tự hành dưới nước và định vị thủy âm trong khảo sát hải dương.",
  },
  {
    id: "exp-vn-06",
    initials: "BT",
    name: "TS Bùi Thu",
    degree: "Tiến sĩ Địa mạo & Động lực Bờ",
    roleTitle: "Phó Trưởng bộ môn Địa lý Biển",
    institution: "Đại học Quốc gia Hà Nội (VNU-HN)",
    institutionId: "org-vn-03",
    country: "VN",
    city: "Hà Nội",
    topics: ["Địa mạo ven biển", "Mô hình số đường bờ", "Xói lở bờ biển"],
    publications: [
      "Numerical modeling of shoreline retreat in tropical monsoon zones (2025)",
      "Sediment transport dynamics during typhoon events (2024)",
    ],
    hIndex: 17,
    activeProjectsCount: 1,
    email: "thu.bui@vnu.edu.vn",
    bio: "Chuyên sâu về mô hình số hình thái đáy biển ven bờ và tương tác sóng - trầm tích trong điều kiện gió mùa.",
  },
  {
    id: "exp-ru-06",
    initials: "SK",
    name: "Dr. Sergei Kozlov",
    degree: "Candidate of Geographical Sciences",
    roleTitle: "Senior Researcher in Coastal Dynamics",
    institution: "Lomonosov Moscow State University (MSU)",
    institutionId: "org-ru-05",
    country: "RU",
    city: "Moskva",
    topics: ["Địa mạo ven biển", "Động lực học sóng", "Mô hình hóa số"],
    publications: [
      "Coastal morphodynamics simulation under variable sea-level conditions (2025)",
      "Coupled hydrodynamic-sedimentological models for estuary systems (2023)",
    ],
    hIndex: 25,
    activeProjectsCount: 2,
    email: "kozlov@geogr.msu.ru",
    bio: "Nghiên cứu động lực học bờ biển và tích hợp dữ liệu trắc đạc địa hình đáy biển vào mô hình dự báo xói lở.",
  },
  {
    id: "exp-vn-07",
    initials: "VL",
    name: "TS Vũ Linh",
    degree: "Tiến sĩ Năng lượng Tái tạo",
    roleTitle: "Trưởng phòng Thí nghiệm Năng lượng Biển",
    institution: "Đại học Bách Khoa - ĐHQG TP.HCM (HCMUT)",
    institutionId: "org-vn-05",
    country: "VN",
    city: "TP. Hồ Chí Minh",
    topics: ["Năng lượng biển", "Vật liệu chuyển đổi", "Tối ưu hóa năng lượng"],
    publications: [
      "Oscillating water column power takeoff optimization for coastal structures (2025)",
      "Piezoelectric and triboelectric energy harvesting in shallow marine environments (2024)",
    ],
    hIndex: 15,
    activeProjectsCount: 1,
    email: "linh.vu@hcmut.edu.vn",
    bio: "Phát triển các thiết bị thu năng lượng sóng quy mô vừa và nhỏ phục vụ trạm quan trắc tự hành ven đảo.",
  },
  {
    id: "exp-ru-07",
    initials: "KR",
    name: "Dr. Kirill Romanov",
    degree: "Candidate of Technical Sciences",
    roleTitle: "Lead Engineer in Offshore Renewable Systems",
    institution: "Far Eastern Federal University (FEFU)",
    institutionId: "org-ru-06",
    country: "RU",
    city: "Vladivostok",
    topics: ["Năng lượng biển", "Thủy khí động lực", "Tuabin dòng chảy"],
    publications: [
      "Hydrokinetic turbine blade design for turbulent tidal channels (2025)",
      "Experimental validation of small-scale wave converters (2024)",
    ],
    hIndex: 20,
    activeProjectsCount: 2,
    email: "romanov.k@fefu.ru",
    bio: "Thử nghiệm tuabin thủy động lực học và vật liệu composite nhẹ cho hệ thống khai thác năng lượng dòng chảy.",
  },
  {
    id: "exp-vn-08",
    initials: "DH",
    name: "TS Đỗ Hùng",
    degree: "Tiến sĩ Hải dương học Vật lý",
    roleTitle: "Phó Viện trưởng phụ trách Chuyên môn",
    institution: "Viện Hải dương học (IO VAST)",
    institutionId: "org-vn-02",
    country: "VN",
    city: "Nha Trang",
    topics: ["Hải dương học", "Dòng chảy ven bờ", "Quan trắc trạm phao"],
    publications: [
      "Bilateral analysis of upwelling dynamics in the South China Sea (2025)",
      "Moored buoy network telemetry and calibration protocols (2023)",
    ],
    hIndex: 26,
    activeProjectsCount: 3,
    email: "hung.do@vnio.vast.vn",
    bio: "Trưởng đoàn nhiều chuyến khảo sát liên hợp Việt - Nga trên tàu Viện sĩ Oparin và tàu Lavrentyev.",
  },
  {
    id: "exp-ru-08",
    initials: "MO",
    name: "Dr. Maria Orlova",
    degree: "Candidate of Phys-Math Sciences",
    roleTitle: "Head of Physical Oceanography Group",
    institution: "Far Eastern Branch of the Russian Academy of Sciences (FEB RAS)",
    institutionId: "org-ru-01",
    country: "RU",
    city: "Vladivostok",
    topics: ["Hải dương học", "Hải lưu nhiệt đới", "Mô hình hoàn lưu"],
    publications: [
      "Mesoscale eddies and their thermal signatures in tropical-subtropical basins (2025)",
      "Satellite altimetry validation using coastal tide gauge networks (2024)",
    ],
    hIndex: 28,
    activeProjectsCount: 2,
    email: "orlova.m@dvo.ru",
    bio: "Chuyên gia mô hình hóa hoàn lưu đại dương và đối chiếu dữ liệu viễn thám cao độ vệ tinh với trạm mặt đất.",
  },
  {
    id: "exp-vn-09",
    initials: "LH",
    name: "TS Lương Hà",
    degree: "Tiến sĩ Hóa phân tích & Cảm biến",
    roleTitle: "Trưởng phòng Thí nghiệm Cảm biến Hóa sinh",
    institution: "Đại học Quốc gia Hà Nội (VNU-HN)",
    institutionId: "org-vn-03",
    country: "VN",
    city: "Hà Nội",
    topics: ["Cảm biến", "Hóa phân tích biển", "Vật liệu nano"],
    publications: [
      "Electrochemical sensing of heavy metal trace elements in saline water (2025)",
      "Nanoporous carbon electrodes for durable marine sensors (2024)",
    ],
    hIndex: 18,
    activeProjectsCount: 1,
    email: "ha.luong@vnu.edu.vn",
    bio: "Phát triển cảm biến điện hóa siêu nhạy phục vụ quan trắc tự động ô nhiễm kim loại nặng trong nước biển.",
  },
  {
    id: "exp-ru-09",
    initials: "OS",
    name: "Dr. Olga Smirnova",
    degree: "Candidate of Chemical Sciences",
    roleTitle: "Lead Researcher in Sensor Materials",
    institution: "National University of Science and Technology MISIS",
    institutionId: "org-ru-02",
    country: "RU",
    city: "Moskva",
    topics: ["Cảm biến", "Điện hóa học", "Vật liệu bền mặn"],
    publications: [
      "Corrosion-resistant metal-oxide coatings for in-situ marine probes (2025)",
      "Miniaturized potentiometric sensors for long-term ocean deployment (2023)",
    ],
    hIndex: 23,
    activeProjectsCount: 1,
    email: "smirnova.o@misis.ru",
    bio: "Thiết kế lớp phủ màng mỏng oxit kim loại bảo vệ điện cực cảm biến hoạt động dài ngày dưới biển sâu.",
  },
  {
    id: "exp-vn-10",
    initials: "NT",
    name: "TS Nguyễn Thảo",
    degree: "Tiến sĩ Kinh tế Môi trường & Khí hậu",
    roleTitle: "Viện trưởng Viện Nghiên cứu Đô thị Ven biển",
    institution: "Đại học Kinh tế Quốc dân (NEU)",
    institutionId: "org-vn-06",
    country: "VN",
    city: "Hà Nội",
    topics: ["Khí hậu", "Đô thị ven biển", "Đánh giá tổn thương"],
    publications: [
      "Urban vulnerability assessment to sea level rise in Central Vietnam (2025)",
      "Spatial econometric analysis of coastal infrastructure risk (2024)",
    ],
    hIndex: 16,
    activeProjectsCount: 2,
    email: "thao.nguyen@neu.edu.vn",
    bio: "Nghiên cứu chính sách thích ứng biến đổi khí hậu và mô hình hóa tác động tổn thương hệ thống hạ tầng đô thị ven biển.",
  },
  {
    id: "exp-ru-10",
    initials: "IB",
    name: "Dr. Irina Belova",
    degree: "Candidate of Economic Sciences",
    roleTitle: "Director of Spatial Analytics Center",
    institution: "HSE University (National Research University Higher School of Economics)",
    institutionId: "org-ru-07",
    country: "RU",
    city: "Moskva",
    topics: ["Khí hậu", "Phân tích không gian", "Kinh tế học đô thị"],
    publications: [
      "Spatial modeling of climate transition risks for coastal agglomerations (2025)",
      "Multicriteria decision analysis for flood mitigation investment (2024)",
    ],
    hIndex: 22,
    activeProjectsCount: 2,
    email: "belova@hse.ru",
    bio: "Chuyên gia về phân tích dữ liệu không gian và đánh giá đa tiêu chí cho các dự án quy hoạch đô thị thích ứng khí hậu.",
  },
  {
    id: "exp-vn-11",
    initials: "HL",
    name: "TS Hoàng Long",
    degree: "Tiến sĩ Địa chất & Khoáng sản Biển",
    roleTitle: "Trưởng phòng Bản đồ Địa chất Biển",
    institution: "Viện Khoa học Địa chất và Khoáng sản (VIGMR)",
    institutionId: "org-vn-07",
    country: "VN",
    city: "Hà Nội",
    topics: ["Địa chất biển", "Trầm tích đáy", "Khoáng sản biển"],
    publications: [
      "Benthic sediment distribution and mineralogy in the Gulf of Tonkin (2025)",
      "Geophysical surveying of nearshore fault systems (2023)",
    ],
    hIndex: 14,
    activeProjectsCount: 1,
    email: "long.hoang@vigmr.vn",
    bio: "Chủ trì xây dựng bộ cơ sở dữ liệu địa chất khoáng sản đáy biển nông và lập bản đồ kiến tạo ven bờ.",
  },
  {
    id: "exp-ru-11",
    initials: "DL",
    name: "Dr. Dmitri Levin",
    degree: "Doctor of Geological-Mineralogical Sciences",
    roleTitle: "Head of Marine Geochemistry Laboratory",
    institution: "V.I. Vernadsky Institute of Geochemistry and Analytical Chemistry (GEOKHI RAS)",
    institutionId: "org-ru-08",
    country: "RU",
    city: "Moskva",
    topics: ["Địa chất biển", "Địa hóa học", "Khoáng sản biển"],
    publications: [
      "Trace element geochemistry of marine manganese nodules and crusts (2025)",
      "Isotopic markers of sedimentary provenance in Western Pacific basins (2024)",
    ],
    hIndex: 30,
    activeProjectsCount: 2,
    email: "levin@geokhi.ru",
    bio: "Nghiên cứu địa hóa đồng vị trầm tích biển sâu và quá trình hình thành kết hạch sắt-mangan dưới đáy đại dương.",
  },
  {
    id: "exp-vn-12",
    initials: "TN",
    name: "GS.TS Trần Đình Nam",
    degree: "Giáo sư, Tiến sĩ Khoa học",
    roleTitle: "Chủ tịch Hội đồng Khoa học Vật liệu Biển",
    institution: "Viện Hải dương học (IO VAST)",
    institutionId: "org-vn-02",
    country: "VN",
    city: "Nha Trang",
    topics: ["Vật liệu mới", "Ăn mòn biển", "Khoa học biển"],
    publications: [
      "Forty years of Vietnam-Russia scientific cooperation in oceanography (2025)",
      "Durability of polymer composites in tropical offshore conditions (2024)",
    ],
    hIndex: 38,
    activeProjectsCount: 3,
    email: "nam.tran@vnio.vast.vn",
    bio: "Nhà khoa học kỳ cựu với hơn 35 năm kinh nghiệm hợp tác nghiên cứu hải dương học và vật liệu biển với các viện thuộc RAS.",
  },
  {
    id: "exp-ru-12",
    initials: "AM",
    name: "Prof. Alexei Morozov",
    degree: "Doctor of Biological Sciences, Corresponding Member of RAS",
    roleTitle: "Director of Institute of Marine Biology",
    institution: "Far Eastern Branch of the Russian Academy of Sciences (FEB RAS)",
    institutionId: "org-ru-01",
    country: "RU",
    city: "Vladivostok",
    topics: ["Sinh học biển", "Hải dương học", "Vật liệu sinh học"],
    publications: [
      "Comparative biodiversity of Northwest Pacific and South China Sea shelf fauna (2025)",
      "Marine bioactive compounds for tropical biomedical applications (2024)",
    ],
    hIndex: 41,
    activeProjectsCount: 3,
    email: "morozov.a@dvo.ru",
    bio: "Viện sĩ Thông tấn Viện Hàn lâm Khoa học Nga, đồng chủ nhiệm nhiều đề tài nghiên cứu hợp tác trọng điểm song phương.",
  },
  {
    id: "exp-vn-13",
    initials: "VK",
    name: "TS Vũ Kim Dung",
    degree: "Tiến sĩ Công nghệ Sinh học",
    roleTitle: "Trưởng nhóm Hoạt chất Sinh học Biển",
    institution: "Viện Khoa học & Công nghệ Việt Nam - Hàn Quốc (VKIST)",
    institutionId: "org-vn-08",
    country: "VN",
    city: "Hà Nội",
    topics: ["Công nghệ sinh học", "Hợp chất tự nhiên", "Dược liệu biển"],
    publications: [
      "Screening of secondary metabolites from tropical soft corals (2025)",
      "Enzyme-assisted extraction of marine polysaccharides (2024)",
    ],
    hIndex: 17,
    activeProjectsCount: 1,
    email: "dung.vu@vkist.gov.vn",
    bio: "Chiết xuất và tinh sạch các hợp chất có hoạt tính sinh học từ sinh vật biển nhiệt đới phục vụ y sinh và mỹ phẩm.",
  },
  {
    id: "exp-ru-13",
    initials: "TG",
    name: "Dr. Tatyana Gerasimova",
    degree: "Doctor of Chemical Sciences",
    roleTitle: "Lead Scientist in Natural Products Chemistry",
    institution: "G.B. Elyakov Pacific Institute of Bioorganic Chemistry (PIBOC FEB RAS)",
    institutionId: "org-ru-09",
    country: "RU",
    city: "Vladivostok",
    topics: ["Hóa sinh hữu cơ", "Hợp chất tự nhiên", "Dược phẩm biển"],
    publications: [
      "Structural elucidation of triterpene glycosides from marine invertebrates (2025)",
      "Cytotoxic properties of deep-sea sponge alkaloids (2023)",
    ],
    hIndex: 29,
    activeProjectsCount: 2,
    email: "gerasimova@piboc.dvo.ru",
    bio: "Chuyên gia xác định cấu trúc phân tử các hợp chất glycoside và alkaloid chiết xuất từ hải miên và sinh vật biển sâu.",
  },
];

export function getExpertById(id: string): Expert | undefined {
  return DEMO_EXPERTS.find((expert) => expert.id === id);
}

export function getExpertsByCountry(country: "VN" | "RU"): Expert[] {
  return DEMO_EXPERTS.filter((expert) => expert.country === country);
}

export function getExpertsByTopic(topic: string): Expert[] {
  return DEMO_EXPERTS.filter((expert) => expert.topics.some((t) => t.toLowerCase().includes(topic.toLowerCase())));
}
