export type IamUserStatus = "ACTIVE" | "INVITED" | "SUSPENDED" | "DEACTIVATED";
export type IamAssignmentScope = "PLATFORM" | "ORGANIZATION" | "REVIEW_BOARD";

export type IamDemoUser = {
  id: string;
  username: string;
  fullName: string;
  email: string;
  institution: string;
  institutionId?: string;
  country: "VN" | "RU";
  status: IamUserStatus;
  roles: string[];
  scope: IamAssignmentScope;
  scopeContext?: string;
  mfaEnabled: boolean;
  lastActiveAt: string;
  capabilities: string[];
};

export type IamAuditEvent = {
  id: string;
  actor: string;
  actorRole: string;
  action: string;
  targetUser: string;
  detail: string;
  timestamp: string;
  outcome: "SUCCESS" | "DENIED" | "REVOKED";
};

export const DEMO_IAM_USERS: IamDemoUser[] = [
  {
    id: "usr-01",
    username: "admin.system",
    fullName: "System Administrator",
    email: "sysadmin@vnru-network.org",
    institution: "VN–RU Foundation Secretariat",
    country: "VN",
    status: "ACTIVE",
    roles: ["SUPER_ADMIN", "IAM_ADMIN"],
    scope: "PLATFORM",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 17:45",
    capabilities: ["iam.roles.manage", "iam.users.manage", "audit.security.view"],
  },
  {
    id: "usr-02",
    username: "manager.collab",
    fullName: "Nguyễn Văn Điều Phối",
    email: "manager.collab@vnru-network.org",
    institution: "Ban Thư ký Điều phối Hợp tác",
    country: "VN",
    status: "ACTIVE",
    roles: ["COLLABORATION_MANAGER"],
    scope: "PLATFORM",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 17:20",
    capabilities: ["collab.opportunities.create", "collab.screening.manage", "reviews.assignments.manage"],
  },
  {
    id: "usr-03",
    username: "decision.maker",
    fullName: "Hội đồng Ban hành Quyết định",
    email: "foundation.decision@vnru-network.org",
    institution: "Ủy ban Điều hành Quỹ Khoa học Song phương",
    country: "VN",
    status: "ACTIVE",
    roles: ["FOUNDATION_DECISION_MAKER"],
    scope: "PLATFORM",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 16:15",
    capabilities: ["collab.decisions.issue_foundation"],
  },
  {
    id: "usr-04",
    username: "mai.le",
    fullName: "PGS.TS Lê Thị Mai",
    email: "mai.le@vast.gov.vn",
    institution: "Viện Hàn lâm KH&CN Việt Nam (VAST)",
    institutionId: "org-vn-01",
    country: "VN",
    status: "ACTIVE",
    roles: ["RESEARCHER"],
    scope: "ORGANIZATION",
    scopeContext: "VAST",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 17:32",
    capabilities: ["collab.proposals.create", "collab.projects.view_owned"],
  },
  {
    id: "usr-05",
    username: "kurchatova.elena",
    fullName: "Prof. Elena Kurchatova",
    email: "kurchatova@misis.ru",
    institution: "NUST MISIS Moskva",
    institutionId: "org-ru-02",
    country: "RU",
    status: "ACTIVE",
    roles: ["RESEARCHER"],
    scope: "ORGANIZATION",
    scopeContext: "MISIS",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 16:50",
    capabilities: ["collab.proposals.create", "collab.projects.view_owned"],
  },
  {
    id: "usr-06",
    username: "minhanh.nguyen",
    fullName: "TS Nguyễn Minh Anh",
    email: "minhanh.nguyen@vast.gov.vn",
    institution: "Viện Hàn lâm KH&CN Việt Nam (VAST)",
    institutionId: "org-vn-01",
    country: "VN",
    status: "ACTIVE",
    roles: ["RESEARCHER"],
    scope: "ORGANIZATION",
    scopeContext: "VAST",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 16:20",
    capabilities: ["collab.proposals.create", "collab.projects.view_owned"],
  },
  {
    id: "usr-07",
    username: "reviewer.07",
    fullName: "Chuyên gia Phản biện #07",
    email: "reviewer07@board.vnru-network.org",
    institution: "Hội đồng Khoa học Vật liệu Biển",
    country: "VN",
    status: "ACTIVE",
    roles: ["REVIEWER"],
    scope: "REVIEW_BOARD",
    scopeContext: "Hội đồng Vật liệu Biển",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 17:15",
    capabilities: ["reviews.assignments.view_assigned", "reviews.evaluations.submit"],
  },
  {
    id: "usr-08",
    username: "reviewer.12",
    fullName: "Chuyên gia Phản biện #12",
    email: "reviewer12@board.vnru-network.org",
    institution: "Hội đồng Dữ liệu Khoa học",
    country: "RU",
    status: "ACTIVE",
    roles: ["REVIEWER"],
    scope: "REVIEW_BOARD",
    scopeContext: "Hội đồng Dữ liệu Khoa học",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 15:30",
    capabilities: ["reviews.assignments.view_assigned", "reviews.evaluations.submit"],
  },
  {
    id: "usr-09",
    username: "reviewer.21",
    fullName: "Chuyên gia Phản biện #21",
    email: "reviewer21@board.vnru-network.org",
    institution: "Hội đồng Hóa lý & Cảm biến",
    country: "RU",
    status: "ACTIVE",
    roles: ["REVIEWER"],
    scope: "REVIEW_BOARD",
    scopeContext: "Hội đồng Cảm biến Biển",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 14:00",
    capabilities: ["reviews.assignments.view_assigned", "reviews.evaluations.submit"],
  },
  {
    id: "usr-10",
    username: "org.vast.rep",
    fullName: "Đại diện Ban HTQT · VAST",
    email: "icd@vast.gov.vn",
    institution: "Viện Hàn lâm KH&CN Việt Nam (VAST)",
    institutionId: "org-vn-01",
    country: "VN",
    status: "ACTIVE",
    roles: ["ORGANIZATION_REPRESENTATIVE"],
    scope: "ORGANIZATION",
    scopeContext: "VAST",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 15:10",
    capabilities: ["collab.proposals.endorse", "collab.projects.view_org"],
  },
  {
    id: "usr-11",
    username: "org.neu.rep",
    fullName: "Đại diện Viện Nghiên cứu Đô thị · NEU",
    email: "rep.neu@neu.edu.vn",
    institution: "Đại học Kinh tế Quốc dân (NEU)",
    institutionId: "org-vn-06",
    country: "VN",
    status: "ACTIVE",
    roles: ["ORGANIZATION_REPRESENTATIVE"],
    scope: "ORGANIZATION",
    scopeContext: "NEU",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 11:20",
    capabilities: ["collab.proposals.endorse", "collab.projects.view_org"],
  },
  {
    id: "usr-12",
    username: "org.febras.rep",
    fullName: "Đại diện Hợp tác Quốc tế · FEB RAS",
    email: "foreign@dvo.ru",
    institution: "Phân viện Viễn Đông - RAS (FEB RAS)",
    institutionId: "org-ru-01",
    country: "RU",
    status: "ACTIVE",
    roles: ["ORGANIZATION_REPRESENTATIVE"],
    scope: "ORGANIZATION",
    scopeContext: "FEB RAS",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 16:40",
    capabilities: ["collab.proposals.endorse", "collab.projects.view_org"],
  },
  {
    id: "usr-13",
    username: "son.pham",
    fullName: "PGS.TS Phạm Sơn",
    email: "son.pham@vnu.edu.vn",
    institution: "Đại học Quốc gia Hà Nội (VNU-HN)",
    institutionId: "org-vn-03",
    country: "VN",
    status: "ACTIVE",
    roles: ["RESEARCHER"],
    scope: "ORGANIZATION",
    scopeContext: "VNU",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 12:10",
    capabilities: ["collab.proposals.create", "collab.projects.view_owned"],
  },
  {
    id: "usr-14",
    username: "dung.vu",
    fullName: "TS Vũ Kim Dung",
    email: "dung.vu@vkist.gov.vn",
    institution: "Viện Khoa học & Công nghệ Việt Nam - Hàn Quốc (VKIST)",
    institutionId: "org-vn-08",
    country: "VN",
    status: "ACTIVE",
    roles: ["RESEARCHER"],
    scope: "ORGANIZATION",
    scopeContext: "VKIST",
    mfaEnabled: false,
    lastActiveAt: "24/08/2026 15:30",
    capabilities: ["collab.proposals.create", "collab.projects.view_owned"],
  },
  {
    id: "usr-15",
    username: "invited.researcher",
    fullName: "Dr. Mikhail Petrov",
    email: "petrov.m@spbstu.ru",
    institution: "SPbPU St. Petersburg",
    institutionId: "org-ru-04",
    country: "RU",
    status: "INVITED",
    roles: ["RESEARCHER"],
    scope: "ORGANIZATION",
    scopeContext: "SPbPU",
    mfaEnabled: false,
    lastActiveAt: "Chưa kích hoạt",
    capabilities: ["collab.proposals.create"],
  },
  {
    id: "usr-16",
    username: "suspended.expert",
    fullName: "TS Lê Quốc Bảo",
    email: "bao.le@hust.edu.vn",
    institution: "Đại học Bách Khoa Hà Nội (HUST)",
    institutionId: "org-vn-04",
    country: "VN",
    status: "SUSPENDED",
    roles: ["RESEARCHER"],
    scope: "ORGANIZATION",
    scopeContext: "HUST",
    mfaEnabled: true,
    lastActiveAt: "10/08/2026 09:15",
    capabilities: [],
  },
  {
    id: "usr-17",
    username: "deactivated.evaluator",
    fullName: "Cựu Chuyên gia Đánh giá #99",
    email: "former99@board.vnru-network.org",
    institution: "Hội đồng Thẩm định Nhiệm kỳ 2024",
    country: "RU",
    status: "DEACTIVATED",
    roles: ["REVIEWER"],
    scope: "REVIEW_BOARD",
    mfaEnabled: false,
    lastActiveAt: "31/12/2025 18:00",
    capabilities: [],
  },
  {
    id: "usr-18",
    username: "reviewer.31",
    fullName: "Chuyên gia Phản biện #31",
    email: "reviewer31@board.vnru-network.org",
    institution: "Hội đồng Sinh thái & Địa chất Biển",
    country: "RU",
    status: "ACTIVE",
    roles: ["REVIEWER"],
    scope: "REVIEW_BOARD",
    scopeContext: "Hội đồng Sinh học Biển",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 16:30",
    capabilities: ["reviews.assignments.view_assigned", "reviews.evaluations.submit"],
  },
  {
    id: "usr-19",
    username: "org.hust.rep",
    fullName: "Đại diện Phòng Hợp tác Đối ngoại · HUST",
    email: "htqt@hust.edu.vn",
    institution: "Đại học Bách Khoa Hà Nội (HUST)",
    institutionId: "org-vn-04",
    country: "VN",
    status: "ACTIVE",
    roles: ["ORGANIZATION_REPRESENTATIVE"],
    scope: "ORGANIZATION",
    scopeContext: "HUST",
    mfaEnabled: true,
    lastActiveAt: "23/08/2026 11:30",
    capabilities: ["collab.proposals.endorse", "collab.projects.view_org"],
  },
  {
    id: "usr-20",
    username: "org.misis.rep",
    fullName: "Đại diện Ban Khoa học Quốc tế · MISIS",
    email: "science.int@misis.ru",
    institution: "NUST MISIS Moskva",
    institutionId: "org-ru-02",
    country: "RU",
    status: "ACTIVE",
    roles: ["ORGANIZATION_REPRESENTATIVE"],
    scope: "ORGANIZATION",
    scopeContext: "MISIS",
    mfaEnabled: true,
    lastActiveAt: "24/08/2026 14:15",
    capabilities: ["collab.proposals.endorse", "collab.projects.view_org"],
  },
];

export const DEMO_AUDIT_EVENTS: IamAuditEvent[] = [
  {
    id: "aud-01",
    actor: "admin.system",
    actorRole: "SUPER_ADMIN",
    action: "Gán quyền vai trò",
    targetUser: "usr-18 (reviewer.31)",
    detail: "Bổ sung vai trò REVIEWER cho Hội đồng Sinh học Biển.",
    timestamp: "24/08/2026 10:00",
    outcome: "SUCCESS",
  },
  {
    id: "aud-02",
    actor: "admin.system",
    actorRole: "SUPER_ADMIN",
    action: "Tạm khóa tài khoản",
    targetUser: "usr-16 (suspended.expert)",
    detail: "Khóa tạm thời theo yêu cầu kiểm tra xung đột lợi ích.",
    timestamp: "10/08/2026 09:15",
    outcome: "SUCCESS",
  },
  {
    id: "aud-03",
    actor: "admin.system",
    actorRole: "SUPER_ADMIN",
    action: "Thu hồi quyền truy cập",
    targetUser: "usr-17 (deactivated.evaluator)",
    detail: "Kết thúc nhiệm kỳ hội đồng thẩm định năm 2024.",
    timestamp: "31/12/2025 18:00",
    outcome: "REVOKED",
  },
  {
    id: "aud-04",
    actor: "manager.collab",
    actorRole: "COLLABORATION_MANAGER",
    action: "Truy cập tài nguyên quản trị",
    targetUser: "Bảng phân quyền IAM",
    detail: "Từ chối truy cập do thiếu quyền iam.roles.manage.",
    timestamp: "24/08/2026 14:20",
    outcome: "DENIED",
  },
];

export function getIamUserById(id: string): IamDemoUser | undefined {
  return DEMO_IAM_USERS.find((user) => user.id === id || user.username === id);
}

export function getIamUsersByRole(role: string): IamDemoUser[] {
  return DEMO_IAM_USERS.filter((user) => user.roles.includes(role));
}

export function getIamUsersByStatus(status: IamUserStatus): IamDemoUser[] {
  return DEMO_IAM_USERS.filter((user) => user.status === status);
}
