export type KnowledgeType = "PUBLICATION" | "DATASET" | "MANUSCRIPT" | "TECHNICAL_REPORT" | "GUIDELINE" | "TOPIC";

export type KnowledgeResource = {
  id: string;
  type: KnowledgeType;
  title: string;
  state: "Đã công bố" | "Đã chia sẻ" | "Bản nháp" | "Nội bộ" | "Đang theo dõi" | "Đã nghiệm thu";
  meta: string;
  summary: string;
  authors?: string[];
  year?: number;
  doi?: string;
  topics: string[];
  accessLevel: "OPEN" | "RESTRICTED" | "INTERNAL";
};

export const DEMO_KNOWLEDGE_RESOURCES: KnowledgeResource[] = [
  {
    id: "k01",
    type: "PUBLICATION",
    title: "Nano-composite chịu ăn mòn trong môi trường biển nhiệt đới",
    state: "Đã công bố",
    meta: "Q1 · 2026 · Vật liệu",
    summary: "Kết quả nghiên cứu về độ bền bề mặt, cơ chế suy giảm liên kết và khả năng chống ăn mòn của lớp phủ nano silica trên hợp kim nhôm trong môi trường biển nhiệt đới.",
    authors: ["PGS.TS Lê Thị Mai", "Prof. Elena Kurchatova", "GS.TS Trần Đình Nam"],
    year: 2026,
    doi: "10.1016/j.corsci.2026.110842",
    topics: ["Vật liệu mới", "Chống ăn mòn", "Vật liệu sinh học"],
    accessLevel: "OPEN",
  },
  {
    id: "k02",
    type: "DATASET",
    title: "Chuỗi quan trắc độ mặn và nhiệt độ trạm Hòn Mun 2024–2026",
    state: "Đã chia sẻ",
    meta: "Hải dương học · 18.4 GB",
    summary: "Bộ dữ liệu đo đạc liên tục 10 phút/lần về nhiệt độ, độ mặn, độ sâu và dòng chảy ngầm phục vụ đối chiếu dữ liệu môi trường giữa hai nhóm nghiên cứu Việt Nam – Liên bang Nga.",
    authors: ["TS Đỗ Hùng", "Dr. Maria Orlova", "TS Trần Hải"],
    year: 2026,
    doi: "10.5281/zenodo.8429103",
    topics: ["Hải dương học", "Dữ liệu quan trắc", "Trạm phao"],
    accessLevel: "OPEN",
  },
  {
    id: "k03",
    type: "MANUSCRIPT",
    title: "Biến tính bề mặt silica cho lớp phủ composite polyme nhiệt đới",
    state: "Bản nháp",
    meta: "Đồng tác giả VN–RU · Bản thảo gửi tạp chí",
    summary: "Bản thảo bài báo khoa học đang hoàn thiện trước khi gửi bình duyệt tại tạp chí Progress in Organic Coatings.",
    authors: ["PGS.TS Lê Thị Mai", "Prof. Elena Kurchatova"],
    year: 2026,
    topics: ["Vật liệu mới", "Hóa bề mặt"],
    accessLevel: "INTERNAL",
  },
  {
    id: "k04",
    type: "TECHNICAL_REPORT",
    title: "Quy trình thử nghiệm gia tốc môi trường biển trong buồng phun muối",
    state: "Nội bộ",
    meta: "Quy chuẩn kỹ thuật · Cập nhật 23/08/2026",
    summary: "Tài liệu hướng dẫn vận hành buồng phun muối sương tuần hoàn và phương pháp lấy mẫu đo đạc độ bám dính lớp sơn phủ theo tiêu chuẩn ISO 9227.",
    authors: ["Nhóm nghiên cứu VAST - FEB RAS"],
    year: 2026,
    topics: ["Vật liệu sinh học", "Thử nghiệm gia tốc"],
    accessLevel: "RESTRICTED",
  },
  {
    id: "k05",
    type: "TOPIC",
    title: "Vật liệu mới & công nghệ chế tạo màng mỏng",
    state: "Đang theo dõi",
    meta: "18 chuyên gia liên quan · 6 dự án",
    summary: "Chủ đề tích hợp kết nối các công bố khoa học, hồ sơ chuyên gia và cơ hội cộng tác nghiên cứu trong lĩnh vực vật liệu cấu trúc và chức năng.",
    topics: ["Vật liệu mới", "Màng mỏng", "Nano"],
    accessLevel: "OPEN",
  },
  {
    id: "k06",
    type: "PUBLICATION",
    title: "Mô hình đồ thị không gian-thời gian dự báo nguy cơ sạt lở ven bờ",
    state: "Đã công bố",
    meta: "Q1 · 2025 · Địa chất biển & AI",
    summary: "Ứng dụng mạng nơ-ron đồ thị tích hợp chuỗi dữ liệu độ ẩm đất và lượng mưa vệ tinh để đưa ra cảnh báo sớm sạt lở bờ biển trước 48 giờ.",
    authors: ["TS Nguyễn Minh Anh", "Dr. Ivan Morozov"],
    year: 2025,
    doi: "10.1016/j.geomorph.2025.108920",
    topics: ["AI & Địa chất", "Cảnh báo sớm"],
    accessLevel: "OPEN",
  },
  {
    id: "k07",
    type: "DATASET",
    title: "Atlas số hình thái rạn san hô và sinh vật đáy vịnh Nha Trang",
    state: "Đã chia sẻ",
    meta: "Sinh học biển · 4.2 GB",
    summary: "Bộ sưu tập 12.000 ảnh độ phân giải cao có gắn nhãn phân loại học các loài san hô tạo rạn và hải miên.",
    authors: ["TS Trần Hải", "Dr. Anna Volkova"],
    year: 2025,
    doi: "10.5281/zenodo.7738291",
    topics: ["Sinh học biển", "Phân loại học hình ảnh"],
    accessLevel: "OPEN",
  },
  {
    id: "k08",
    type: "GUIDELINE",
    title: "Khung siêu dữ liệu chuẩn FAIR cho dữ liệu hải dương học song phương",
    state: "Đã nghiệm thu",
    meta: "Tài liệu hướng dẫn · Chuẩn NetCDF/OGC",
    summary: "Đặc tả chuẩn cấu trúc trường dữ liệu, từ điển danh mục thông số và phương pháp mã hóa tọa độ không gian thời gian dùng chung.",
    authors: ["PGS.TS Phạm Sơn", "Dr. Pavel Sidorov"],
    year: 2026,
    topics: ["Dữ liệu khoa học", "Chuẩn hóa FAIR"],
    accessLevel: "OPEN",
  },
  {
    id: "k09",
    type: "PUBLICATION",
    title: "Đặc trưng thủy động lực của phương tiện tự hành AUV vùng nước nông",
    state: "Đã công bố",
    meta: "Scopus · 2026 · Robot biển",
    summary: "Nghiên cứu ảnh hưởng của dòng chảy đáy và độ sâu hạn chế đến độ ổn định quỹ đạo của robot lặn khảo sát sinh thái.",
    authors: ["TS Đặng Quốc", "Prof. Alexei Petrov"],
    year: 2026,
    doi: "10.1016/j.oceaneng.2026.112340",
    topics: ["Robot biển", "Cơ điện tử"],
    accessLevel: "OPEN",
  },
  {
    id: "k10",
    type: "MANUSCRIPT",
    title: "Mô phỏng số biến động đường bờ dải ven biển miền Trung trong bối cảnh triều dâng",
    state: "Bản nháp",
    meta: "Bản thảo gửi Coastal Engineering",
    summary: "Đối sánh kết quả mô hình Delft3D với chuỗi ảnh viễn thám quang học 15 năm qua.",
    authors: ["TS Bùi Thu", "Dr. Sergei Kozlov"],
    year: 2026,
    topics: ["Địa mạo ven biển", "Mô hình hóa số"],
    accessLevel: "INTERNAL",
  },
  {
    id: "k11",
    type: "TECHNICAL_REPORT",
    title: "Báo cáo thử nghiệm nguyên mẫu thiết bị thu hồi năng lượng sóng biển dạng phao",
    state: "Nội bộ",
    meta: "Báo cáo kết quả thử nghiệm bể sóng",
    summary: "Tổng hợp thông số công suất phát điện thực đo tại các tần số sóng khác nhau trong bể thử tạo sóng HCMUT.",
    authors: ["TS Vũ Linh", "Dr. Kirill Romanov"],
    year: 2026,
    topics: ["Năng lượng biển", "Tối ưu hóa năng lượng"],
    accessLevel: "RESTRICTED",
  },
  {
    id: "k12",
    type: "PUBLICATION",
    title: "Cấu trúc nhiệt độ và độ muối các xoáy nhiệt đới Tây Thái Bình Dương",
    state: "Đã công bố",
    meta: "Q1 · 2025 · Hải dương học",
    summary: "Phân tích số liệu trắc diện CTD thu thập từ các chuyến khảo sát chung trên tàu Viện sĩ Oparin.",
    authors: ["TS Đỗ Hùng", "Dr. Maria Orlova"],
    year: 2025,
    doi: "10.1029/2025JC019842",
    topics: ["Hải dương học", "Hải lưu nhiệt đới"],
    accessLevel: "OPEN",
  },
  {
    id: "k13",
    type: "GUIDELINE",
    title: "Quy chuẩn phân tích điện hóa và lưu giữ điện cực cảm biến nước mặn",
    state: "Đã nghiệm thu",
    meta: "Hướng dẫn thực hành phòng lab",
    summary: "Các bước chuẩn bị dung dịch điện ly chuẩn và bảo quản màng nhạy ion khi không vận hành.",
    authors: ["TS Lương Hà", "Dr. Olga Smirnova"],
    year: 2025,
    topics: ["Cảm biến", "Hóa phân tích"],
    accessLevel: "OPEN",
  },
  {
    id: "k14",
    type: "DATASET",
    title: "Bản đồ phân vùng rủi ro tổn thương đô thị ven biển trước nước biển dâng",
    state: "Đã chia sẻ",
    meta: "GIS · Shapefile & GeoTIFF · 1.8 GB",
    summary: "Dữ liệu không gian phân lớp các vùng dân cư, công trình hạ tầng và vùng sinh thái nhạy cảm ngập lụt.",
    authors: ["TS Nguyễn Thảo", "Dr. Irina Belova"],
    year: 2026,
    doi: "10.5281/zenodo.8192014",
    topics: ["Khí hậu", "Đô thị ven biển"],
    accessLevel: "OPEN",
  },
  {
    id: "k15",
    type: "PUBLICATION",
    title: "Thạch học và địa hóa đồng vị trầm tích bồi tụ vịnh Bắc Bộ",
    state: "Đã công bố",
    meta: "Q2 · 2025 · Địa chất biển",
    summary: "Xác định nguồn gốc bồi tích và tốc độ lắng đọng trầm tích cửa sông dựa trên tỷ số đồng vị chì-210 và xê-xi-137.",
    authors: ["TS Hoàng Long", "Dr. Dmitri Levin"],
    year: 2025,
    doi: "10.1016/j.margeo.2025.106890",
    topics: ["Địa chất biển", "Địa hóa học"],
    accessLevel: "OPEN",
  },
  {
    id: "k16",
    type: "TOPIC",
    title: "Công nghệ sinh học biển & hợp chất tự nhiên",
    state: "Đang theo dõi",
    meta: "12 chuyên gia · 4 dự án đang chạy",
    summary: "Theo dõi các công bố về phân lập hợp chất chống oxy hóa, kháng khuẩn và hoạt tính y sinh từ sinh vật biển.",
    topics: ["Công nghệ sinh học", "Hợp chất tự nhiên", "Dược liệu"],
    accessLevel: "OPEN",
  },
  {
    id: "k17",
    type: "TECHNICAL_REPORT",
    title: "Quy trình chiết xuất hoạt chất polysaccharide từ rong biển nhiệt đới",
    state: "Nội bộ",
    meta: "Tài liệu quy trình VKIST - PIBOC",
    summary: "Đặc tả các thông số tối ưu của quá trình chiết xuất có hỗ trợ sóng siêu âm và tinh chế qua màng siêu lọc.",
    authors: ["TS Vũ Kim Dung", "Dr. Tatyana Gerasimova"],
    year: 2026,
    topics: ["Công nghệ sinh học", "Hóa sinh"],
    accessLevel: "RESTRICTED",
  },
  {
    id: "k18",
    type: "PUBLICATION",
    title: "Cảm biến từ kế nguyên tử quang học ứng dụng thăm dò dị thường từ biển",
    state: "Đã công bố",
    meta: "Q1 · 2026 · Vật lý lượng tử",
    summary: "Mô hình hóa và thực nghiệm độ nhạy đầu đo từ kế nguyên tử rubidi trong điều kiện bù từ trường ngoài.",
    authors: ["GS.TS Trần Đình Nam", "Dr. Ivan Morozov"],
    year: 2026,
    doi: "10.1103/PhysRevApplied.2026.044021",
    topics: ["Cảm biến lượng tử", "Địa vật lý"],
    accessLevel: "OPEN",
  },
  {
    id: "k19",
    type: "MANUSCRIPT",
    title: "Điện cực màng nano coban-niken cho phản ứng tách oxy trong nước biển",
    state: "Bản nháp",
    meta: "Bản thảo gửi Applied Catalysis B",
    summary: "Nghiên cứu cơ chế ức chế tạo khí clo và tăng độ bền điện cực trong dung dịch muối ăn nồng độ cao.",
    authors: ["PGS.TS Lê Thị Mai", "Prof. Elena Kurchatova"],
    year: 2026,
    topics: ["Hydro xanh", "Xúc tác điện hóa"],
    accessLevel: "INTERNAL",
  },
  {
    id: "k20",
    type: "GUIDELINE",
    title: "Hướng dẫn bảo mật thông tin và giao thức mã hóa cho mạng phao quan trắc",
    state: "Đã nghiệm thu",
    meta: "Tiêu chuẩn kỹ thuật bảo mật IoT",
    summary: "Khuyến nghị triển khai thuật toán mã hóa nhẹ ASCON và giao thức xác thực nguồn gốc dữ liệu trạm đo phao.",
    authors: ["PGS.TS Phạm Sơn", "Prof. Alexei Petrov"],
    year: 2026,
    topics: ["An ninh mạng · IoT", "An toàn dữ liệu"],
    accessLevel: "OPEN",
  },
  {
    id: "k21",
    type: "DATASET",
    title: "Bộ dữ liệu kiểu gen và chỉ thị phân tử các giống lúa chịu mặn ven biển",
    state: "Đã chia sẻ",
    meta: "Nông nghiệp · Sinh học phân tử · 850 MB",
    summary: "Dữ liệu giải trình tự gen thế hệ mới của 60 giống lúa bản địa vùng đồng bằng ven biển.",
    authors: ["TS Vũ Kim Dung", "Dr. Tatyana Gerasimova"],
    year: 2026,
    doi: "10.5281/zenodo.8329104",
    topics: ["Nông nghiệp · Sinh học", "Chịu mặn"],
    accessLevel: "OPEN",
  },
  {
    id: "k22",
    type: "TOPIC",
    title: "Hải dương học tính toán & Mô hình hoàn lưu biển",
    state: "Đang theo dõi",
    meta: "22 chuyên gia · 8 viện nghiên cứu",
    summary: "Tập hợp các nghiên cứu về mô hình động lực học biển, tương tác biển-khí quyển và dự báo hải lưu.",
    topics: ["Hải dương học", "Mô hình hóa số", "Hải lưu"],
    accessLevel: "OPEN",
  },
  {
    id: "k23",
    type: "TECHNICAL_REPORT",
    title: "Tổng kết chuyến khảo sát địa chấn nông thềm lục địa miền Trung 2025",
    state: "Nội bộ",
    meta: "Báo cáo địa vật lý VIGMR - GEOKHI",
    summary: "Mặt cắt địa chấn phân giải cao phản ánh cấu trúc tầng nông trầm tích đáy biển khu vực nghiên cứu.",
    authors: ["TS Hoàng Long", "Dr. Dmitri Levin"],
    year: 2025,
    topics: ["Địa chất biển", "Địa vật lý"],
    accessLevel: "RESTRICTED",
  },
  {
    id: "k24",
    type: "PUBLICATION",
    title: "Đánh giá 40 năm hợp tác nghiên cứu khoa học biển Việt Nam – Liên bang Nga",
    state: "Đã công bố",
    meta: "Kỷ yếu hội nghị quốc tế · 2025",
    summary: "Tổng quan các thành tựu nổi bật, các công bố chung và định hướng trọng tâm hợp tác khoa học công nghệ biển đến năm 2035.",
    authors: ["GS.TS Trần Đình Nam", "Prof. Alexei Morozov"],
    year: 2025,
    doi: "10.1007/978-981-99-8420-1",
    topics: ["Chiến lược KH & CN", "Hợp tác song phương"],
    accessLevel: "OPEN",
  },
];

export function getKnowledgeResourceById(id: string): KnowledgeResource | undefined {
  return DEMO_KNOWLEDGE_RESOURCES.find((item) => item.id === id);
}

export function getKnowledgeResourcesByType(type: KnowledgeType): KnowledgeResource[] {
  return DEMO_KNOWLEDGE_RESOURCES.filter((item) => item.type === type);
}
