import type { WorkflowNotification, WorkflowRole } from "../demo-v2/types";

export const DEMO_NOTIFICATIONS: WorkflowNotification[] = [
  // RESEARCHER notifications (6 items)
  {
    id: "n01",
    role: "RESEARCHER",
    title: "Hồ sơ cần bổ sung thông tin",
    message: "RU-VN-2026-AI-04 thiếu nguồn dữ liệu dùng chung và phạm vi thử nghiệm ven bờ.",
    href: "/workspace/researcher?view=collaboration&id=p02",
    read: false,
    createdAt: "2 phút trước",
    tone: "warning",
  },
  {
    id: "n02",
    role: "RESEARCHER",
    title: "Sắp đến hạn mốc tiến độ dự án",
    message: "RU-VN-2026-BIO-08 còn 6 ngày đến hạn hoàn tất thử nghiệm gia tốc.",
    href: "/workspace/researcher?view=projects&id=pr02",
    read: false,
    createdAt: "18 phút trước",
    tone: "warning",
  },
  {
    id: "n03",
    role: "RESEARCHER",
    title: "Báo cáo tiến độ đã được duyệt",
    message: "Báo cáo H1/2026 dự án RU-VN-2025-EDDY-21 đã được phê duyệt.",
    href: "/workspace/researcher?view=projects&id=pr07",
    read: true,
    createdAt: "2 giờ trước",
    tone: "success",
  },
  {
    id: "n04",
    role: "RESEARCHER",
    title: "Đề xuất được chấp thuận",
    message: "RU-VN-2025-OCEAN-03 đã có quyết định chính thức từ Hội đồng.",
    href: "/workspace/researcher?view=collaboration&id=p09",
    read: true,
    createdAt: "1 ngày trước",
    tone: "success",
  },
  {
    id: "n05",
    role: "RESEARCHER",
    title: "Cơ hội hợp tác nghiên cứu mới",
    message: "OPP-2026-BIOCHEM: Hợp chất sinh học và dược liệu tự nhiên từ sinh vật biển đã mở tiếp nhận.",
    href: "/workspace/researcher?view=overview",
    read: false,
    createdAt: "3 giờ trước",
    tone: "info",
  },
  {
    id: "n06",
    role: "RESEARCHER",
    title: "Báo cáo tiến độ bị trả lại",
    message: "Báo cáo H1/2026 dự án RU-VN-2025-OCEAN-03 cần bổ sung kiểm chuẩn cảm biến đo độ mặn.",
    href: "/workspace/researcher?view=projects&id=pr01",
    read: false,
    createdAt: "5 giờ trước",
    tone: "warning",
  },

  // REVIEWER notifications (6 items)
  {
    id: "n07",
    role: "REVIEWER",
    title: "Hồ sơ phản biện quá hạn",
    message: "Hồ sơ RU-VN-2026-COAST-06 đã quá hạn đánh giá 1 ngày.",
    href: "/workspace/reviewer?view=evaluation&id=rv02",
    read: false,
    createdAt: "7 phút trước",
    tone: "danger",
  },
  {
    id: "n08",
    role: "REVIEWER",
    title: "Phân công phản biện mới",
    message: "Bạn được phân công đánh giá hồ sơ RU-VN-2026-DATA-03 (hạn 09/09/2026).",
    href: "/workspace/reviewer?view=assignments&id=rv04",
    read: false,
    createdAt: "1 giờ trước",
    tone: "info",
  },
  {
    id: "n09",
    role: "REVIEWER",
    title: "Xác nhận gửi phản biện thành công",
    message: "Đánh giá cho RU-VN-2026-ENERGY-09 (Điểm: 7.20/10) đã gửi sang Cơ quan quyết định.",
    href: "/workspace/reviewer?view=history&id=rv05",
    read: true,
    createdAt: "3 ngày trước",
    tone: "success",
  },
  {
    id: "n10",
    role: "REVIEWER",
    title: "Cảnh báo xung đột lợi ích",
    message: "Phân công RU-VN-2026-NANO-01 bị gắn cờ xung đột đơn vị chủ trì (VAST).",
    href: "/workspace/reviewer?view=assignments&id=rv08",
    read: false,
    createdAt: "4 giờ trước",
    tone: "warning",
  },
  {
    id: "n11",
    role: "REVIEWER",
    title: "Hồ sơ sắp đến hạn đánh giá",
    message: "RU-VN-2026-BIO-08 còn 6 ngày để hoàn thiện bản nháp phản biện.",
    href: "/workspace/reviewer?view=evaluation&id=rv01",
    read: false,
    createdAt: "1 ngày trước",
    tone: "warning",
  },
  {
    id: "n12",
    role: "REVIEWER",
    title: "Phân công phản biện mới",
    message: "Bạn được phân công đánh giá hồ sơ RU-VN-2026-QUANTUM-19.",
    href: "/workspace/reviewer?view=assignments&id=rv09",
    read: true,
    createdAt: "2 ngày trước",
    tone: "info",
  },

  // ORGANIZATION_REPRESENTATIVE notifications (6 items)
  {
    id: "n13",
    role: "ORGANIZATION_REPRESENTATIVE",
    title: "Cần xác nhận bảo trợ hồ sơ",
    message: "RU-VN-2026-CLIMATE-11 đang chờ tổ chức xác nhận trước hạn 01/09/2026.",
    href: "/workspace/organization?view=endorsements&id=en01",
    read: false,
    createdAt: "12 phút trước",
    tone: "warning",
  },
  {
    id: "n14",
    role: "ORGANIZATION_REPRESENTATIVE",
    title: "Dự án mới trong tổ chức được kích hoạt",
    message: "Dự án RU-VN-2025-OCEAN-03 đã chính thức chuyển sang giai đoạn thực hiện.",
    href: "/workspace/organization?view=projects&id=pr01",
    read: true,
    createdAt: "2 ngày trước",
    tone: "success",
  },
  {
    id: "n15",
    role: "ORGANIZATION_REPRESENTATIVE",
    title: "Dự án có mốc tiến độ hoàn thành",
    message: "RU-VN-2026-BIO-08 vừa hoàn tất mốc 'Thiết lập mẫu chuẩn'.",
    href: "/workspace/organization?view=projects&id=pr02",
    read: false,
    createdAt: "4 giờ trước",
    tone: "info",
  },
  {
    id: "n16",
    role: "ORGANIZATION_REPRESENTATIVE",
    title: "Hồ sơ tổ chức cần bổ sung tài liệu",
    message: "Đề xuất RU-VN-2026-AI-04 yêu cầu bổ sung danh mục thiết bị cụm GPU dùng chung.",
    href: "/workspace/organization?view=endorsements&id=en02",
    read: false,
    createdAt: "6 giờ trước",
    tone: "warning",
  },
  {
    id: "n17",
    role: "ORGANIZATION_REPRESENTATIVE",
    title: "Đã xác nhận cam kết hạ tầng",
    message: "Hồ sơ RU-VN-2026-MAR-02 đã hoàn tất ký bảo trợ và chuyển sang điều phối.",
    href: "/workspace/organization?view=endorsements&id=en03",
    read: true,
    createdAt: "3 ngày trước",
    tone: "success",
  },
  {
    id: "n18",
    role: "ORGANIZATION_REPRESENTATIVE",
    title: "Từ chối xác nhận đề xuất",
    message: "Hồ sơ RU-VN-2026-ROBOT-05 không được tổ chức phê duyệt do không đủ nguồn lực.",
    href: "/workspace/organization?view=endorsements&id=en04",
    read: true,
    createdAt: "4 ngày trước",
    tone: "danger",
  },

  // COLLABORATION_MANAGER notifications (5 items)
  {
    id: "n19",
    role: "COLLABORATION_MANAGER",
    title: "Hồ sơ mới nộp vào hàng đợi",
    message: "RU-VN-2026-DATA-03 vừa được nộp và sẵn sàng cho vòng sàng lọc hình thức.",
    href: "/workspace/collaboration?view=screening&id=p04",
    read: false,
    createdAt: "4 phút trước",
    tone: "info",
  },
  {
    id: "n20",
    role: "COLLABORATION_MANAGER",
    title: "Hồ sơ chưa phân công phản biện",
    message: "RU-VN-2026-MAR-02 đã đủ điều kiện nhưng chưa chỉ định chuyên gia đánh giá.",
    href: "/workspace/collaboration?view=assignments&id=rv03",
    read: false,
    createdAt: "28 phút trước",
    tone: "warning",
  },
  {
    id: "n21",
    role: "COLLABORATION_MANAGER",
    title: "Báo cáo tiến độ mới chờ duyệt",
    message: "Báo cáo Q2/2026 của dự án RU-VN-2026-BIO-08 đã được nộp.",
    href: "/workspace/collaboration?view=reports&id=rp01",
    read: false,
    createdAt: "1 giờ trước",
    tone: "info",
  },
  {
    id: "n22",
    role: "COLLABORATION_MANAGER",
    title: "Phát hiện xung đột lợi ích phân công",
    message: "Phân công RU-VN-2026-NANO-01 cho Chuyên gia #21 vi phạm quy tắc độc lập.",
    href: "/workspace/collaboration?view=assignments&id=rv08",
    read: false,
    createdAt: "2 giờ trước",
    tone: "danger",
  },
  {
    id: "n23",
    role: "COLLABORATION_MANAGER",
    title: "Hồ sơ hoàn tất phản biện",
    message: "Hồ sơ RU-VN-2026-ENERGY-09 đã có đủ phản biện, sẵn sàng chuyển Cơ quan quyết định.",
    href: "/workspace/collaboration?view=overview",
    read: true,
    createdAt: "1 ngày trước",
    tone: "success",
  },

  // FOUNDATION_DECISION_MAKER notifications (5 items)
  {
    id: "n24",
    role: "FOUNDATION_DECISION_MAKER",
    title: "Hồ sơ sẵn sàng ban hành quyết định",
    message: "RU-VN-2026-BIO-08 đã có kết quả phản biện tổng hợp (8.45/10).",
    href: "/workspace/decisions?view=queue&id=dc04",
    read: false,
    createdAt: "6 phút trước",
    tone: "info",
  },
  {
    id: "n25",
    role: "FOUNDATION_DECISION_MAKER",
    title: "Quyết định đã ban hành thành công",
    message: "RU-VN-2025-OCEAN-03 đã được chấp thuận phê duyệt triển khai dự án.",
    href: "/workspace/decisions?view=history&id=dc02",
    read: true,
    createdAt: "3 ngày trước",
    tone: "success",
  },
  {
    id: "n26",
    role: "FOUNDATION_DECISION_MAKER",
    title: "Yêu cầu chỉnh sửa đề xuất",
    message: "RU-VN-2026-ENERGY-09 đã chuyển trạng thái yêu cầu hoàn thiện lại mục tiêu.",
    href: "/workspace/decisions?view=history&id=dc01",
    read: true,
    createdAt: "2 ngày trước",
    tone: "warning",
  },
  {
    id: "n27",
    role: "FOUNDATION_DECISION_MAKER",
    title: "Quyết định không chấp thuận hồ sơ",
    message: "RU-VN-2026-SENSOR-10 đã ban hành quyết định từ chối do không đạt tính khả thi.",
    href: "/workspace/decisions?view=history&id=dc03",
    read: true,
    createdAt: "4 ngày trước",
    tone: "danger",
  },
  {
    id: "n28",
    role: "FOUNDATION_DECISION_MAKER",
    title: "Hồ sơ mới chuyển vào hàng đợi quyết định",
    message: "RU-VN-2026-SEDIMENT-20 đã hoàn tất đánh giá chuyên gia với điểm 8.50/10.",
    href: "/workspace/decisions?view=queue&id=dc05",
    read: false,
    createdAt: "5 giờ trước",
    tone: "info",
  },
];

export function getNotificationsByRole(role: WorkflowRole): WorkflowNotification[] {
  return DEMO_NOTIFICATIONS.filter((item) => item.role === role);
}

export function getUnreadNotificationsByRole(role: WorkflowRole): WorkflowNotification[] {
  return DEMO_NOTIFICATIONS.filter((item) => item.role === role && !item.read);
}
