import type { Opportunity } from "../demo-v2/types";

export type DetailedOpportunity = Opportunity & {
  summary?: string;
  scope?: string;
  objective?: string;
  topics?: string[];
  relatedExpertIds?: string[];
  eligiblePartners?: string;
  publishedAt?: string;
  guidelines?: string[];
};

export const DEMO_OPPORTUNITIES: DetailedOpportunity[] = [
  {
    id: "op01",
    code: "OPP-2026-MARINE",
    title: "Vật liệu và cảm biến cho môi trường biển nhiệt đới",
    field: "Vật liệu · Cảm biến",
    closes: "30/09/2026",
    state: "PUBLISHED",
    summary: "Hợp tác phát triển vật liệu nano-composite, màng phủ chống bám bẩn và cảm biến điện hóa bền môi trường nước mặn.",
    scope: "Việt Nam ↔ Liên bang Nga (Viện/Trường song phương)",
    objective: "Tạo ra các mẫu thử nghiệm vật liệu và thiết bị cảm biến chịu được độ mặn và độ ẩm cao trong điều kiện biển nhiệt đới.",
    topics: ["Vật liệu mới", "Chống ăn mòn", "Cảm biến biển"],
    relatedExpertIds: ["exp-vn-01", "exp-ru-01", "exp-vn-09", "exp-ru-09"],
    eligiblePartners: "Tối thiểu 01 viện/trường phía Việt Nam và 01 tổ chức nghiên cứu thuộc Viện Hàn lâm Khoa học Nga hoặc trường đại học LB Nga.",
    publishedAt: "15/06/2026",
    guidelines: [
      "Hồ sơ cần thuyết minh rõ tính bổ trợ về cơ sở vật chất giữa hai bên.",
      "Cam kết chia sẻ dữ liệu thử nghiệm gia tốc và đo kiểm bề mặt.",
      "Không yêu cầu hoặc bao gồm các điều khoản tài chính/ngân sách thương mại.",
    ],
  },
  {
    id: "op02",
    code: "OPP-2026-AI",
    title: "AI cho quan trắc và dự báo rủi ro ven biển",
    field: "AI · Địa chất biển",
    closes: "15/10/2026",
    state: "DRAFT",
    summary: "Ứng dụng mô hình học sâu và đồ thị không gian-thời gian dự báo sớm sạt lở bờ biển, triều cường và tai biến địa chất.",
    scope: "Nhóm nghiên cứu chuyên sâu về Khoa học Dữ liệu và Khoa học Trái đất",
    objective: "Xây dựng khung mô hình học máy tích hợp dữ liệu viễn thám và chuỗi số liệu quan trắc trạm đo ven bờ.",
    topics: ["AI & Địa chất", "Học sâu", "Cảnh báo sớm"],
    relatedExpertIds: ["exp-vn-02", "exp-ru-02", "exp-vn-06", "exp-ru-06"],
    eligiblePartners: "Các phòng thí nghiệm trọng điểm về AI và các viện nghiên cứu địa chất, hải dương học hai nước.",
    guidelines: [
      "Phương pháp mô hình hóa phải có khả năng kiểm chứng trên chuỗi dữ liệu thực tế tối thiểu 3 năm.",
      "Bộ mã nguồn thuật toán và tài liệu kỹ thuật tuân thủ chuẩn mở cho nhóm nghiên cứu.",
    ],
  },
  {
    id: "op03",
    code: "OPP-2026-DATA",
    title: "Hạ tầng dữ liệu khoa học song phương VN–RU",
    field: "Dữ liệu khoa học",
    closes: "10/10/2026",
    state: "PUBLISHED",
    summary: "Xây dựng đường ống liên thông, chuẩn hóa siêu dữ liệu và cổng truy cập dữ liệu quan trắc hải dương học mở.",
    scope: "Viện dữ liệu và cơ sở đào tạo đại học",
    objective: "Thiết lập quy chuẩn dữ liệu FAIR song phương cho các chuỗi dữ liệu hải dương học và môi trường biển.",
    topics: ["Dữ liệu khoa học", "Liên thông hệ thống", "Chuẩn hóa FAIR"],
    relatedExpertIds: ["exp-vn-04", "exp-ru-04", "exp-vn-08", "exp-ru-08"],
    eligiblePartners: "Đơn vị quản lý cơ sở dữ liệu khoa học cấp viện hoặc trường đại học có trung tâm máy chủ.",
    publishedAt: "01/07/2026",
    guidelines: [
      "Hệ thống phải hỗ trợ chuẩn dữ liệu NetCDF, OGC và bộ từ điển thuật ngữ chuyên ngành song ngữ/tam ngữ.",
      "Đảm bảo an toàn phân quyền truy cập theo từng mức độ mở của tập dữ liệu.",
    ],
  },
  {
    id: "op04",
    code: "OPP-2026-COAST",
    title: "Đô thị và hệ sinh thái ven biển trước biến đổi khí hậu",
    field: "Khí hậu · Sinh thái",
    closes: "01/09/2026",
    state: "CLOSED",
    summary: "Đánh giá tổn thương và xây dựng mô hình mô phỏng biến động đường bờ cho các đô thị ven biển miền Trung.",
    scope: "Nhóm nghiên cứu liên ngành Kinh tế - Địa lý - Khí hậu",
    objective: "Cung cấp cơ sở khoa học và bộ tiêu chí đánh giá rủi ro ngập lụt ven bờ cho quy hoạch không gian đô thị.",
    topics: ["Khí hậu", "Đô thị ven biển", "Địa mạo"],
    relatedExpertIds: ["exp-vn-10", "exp-ru-10", "exp-vn-06", "exp-ru-06"],
    eligiblePartners: "Các trường đại học khối kinh tế, quy hoạch không gian phối hợp cùng viện nghiên cứu địa mạo biển.",
    publishedAt: "01/05/2026",
    guidelines: [
      "Chương trình đã đóng đợt tiếp nhận hồ sơ, hiện đang trong giai đoạn triển khai dự án đã được phê duyệt.",
    ],
  },
  {
    id: "op05",
    code: "OPP-2026-ROBOT",
    title: "Robot và thiết bị tự hành khảo sát vùng nước nông",
    field: "Robot biển",
    closes: "20/11/2026",
    state: "DRAFT",
    summary: "Thiết kế chế tạo phương tiện tự hành dưới nước AUV/USV phục vụ tuần tra sinh thái và lập bản đồ đáy cạn nhiệt đới.",
    scope: "Khoa Cơ khí - Cơ điện tử và Tự động hóa",
    objective: "Hoàn thiện mẫu chế thử phương tiện lặn tự hành có khả năng hoạt động ổn định trong vùng dòng chảy ngầm phức tạp.",
    topics: ["Robot biển", "Cơ điện tử", "Thủy âm định vị"],
    relatedExpertIds: ["exp-vn-05", "exp-ru-05"],
    eligiblePartners: "Khoa Cơ điện tử các trường đại học kỹ thuật phối hợp với các viện nghiên cứu cơ học biển.",
    guidelines: [
      "Yêu cầu báo cáo kiểm chứng mô hình thủy động lực trong bể thử trước khi tích hợp thiết bị trên biển thực tế.",
    ],
  },
  {
    id: "op06",
    code: "OPP-2026-BIOCHEM",
    title: "Hợp chất sinh học và dược liệu tự nhiên từ sinh vật biển",
    field: "Công nghệ sinh học",
    closes: "25/10/2026",
    state: "PUBLISHED",
    summary: "Chiết xuất, định danh cấu trúc và đánh giá hoạt tính sinh học của các hợp chất tự nhiên từ hải miên và san hô mềm.",
    scope: "Viện Hóa sinh và Trung tâm Công nghệ sinh học",
    objective: "Xác định các phân tử hoạt tính tiềm năng phục vụ định hướng nghiên cứu y sinh và bảo quản sinh thái biển.",
    topics: ["Công nghệ sinh học", "Hóa sinh", "Hợp chất tự nhiên"],
    relatedExpertIds: ["exp-vn-13", "exp-ru-13", "exp-vn-03", "exp-ru-03"],
    eligiblePartners: "Viện Hóa sinh hữu cơ, Viện Công nghệ sinh học và các phòng lab chuyên ngành hai nước.",
    publishedAt: "20/07/2026",
    guidelines: [
      "Tuân thủ nghiêm ngặt quy định quốc tế về bảo tồn nguồn gen và đa dạng sinh học biển.",
      "Ghi nhận rõ xuất xứ mẫu vật và phương pháp lưu giữ mẫu chuẩn.",
    ],
  },
  {
    id: "op07",
    code: "OPP-2026-ENERGY",
    title: "Thiết bị thu hồi năng lượng sóng và dòng chảy biển quy mô nhỏ",
    field: "Năng lượng biển",
    closes: "12/10/2026",
    state: "PUBLISHED",
    summary: "Nghiên cứu cánh tuabin và cụm máy phát điện áp điện/điện ma sát thu năng lượng sóng cấp nguồn cho phao quan trắc.",
    scope: "Khoa Kỹ thuật Năng lượng và Thủy khí",
    objective: "Thiết kế bộ chuyển đổi năng lượng hoạt động liên tục tại các trạm đo ven đảo cách xa bờ.",
    topics: ["Năng lượng biển", "Tối ưu hóa năng lượng", "Vật liệu chuyển đổi"],
    relatedExpertIds: ["exp-vn-07", "exp-ru-07"],
    eligiblePartners: "Các trường đại học bách khoa và viện nghiên cứu năng lượng tái tạo.",
    publishedAt: "10/07/2026",
    guidelines: [
      "Cần có bản vẽ thiết kế nguyên lý và kết quả mô phỏng hiệu suất chuyển đổi năng lượng trong điều kiện sóng mùa hè/mùa đông.",
    ],
  },
  {
    id: "op08",
    code: "OPP-2026-GEOLOGY",
    title: "Cơ sở dữ liệu địa chất khoáng sản và kiến tạo đáy biển",
    field: "Địa chất biển",
    closes: "05/11/2026",
    state: "PUBLISHED",
    summary: "Xây dựng hệ thống bản đồ số địa chất trầm tích và phân tích đặc trưng địa hóa các kết hạch khoáng vật biển.",
    scope: "Viện Địa chất và Khoáng sản song phương",
    objective: "Chuẩn hóa atlas cấu trúc địa chất nông và cơ chế lắng đọng trầm tích vùng thềm lục địa.",
    topics: ["Địa chất biển", "Địa hóa học", "Bản đồ kiến tạo"],
    relatedExpertIds: ["exp-vn-11", "exp-ru-11", "exp-vn-08", "exp-ru-08"],
    eligiblePartners: "Viện nghiên cứu địa chất và phòng thí nghiệm phân tích địa hóa đồng vị.",
    publishedAt: "18/07/2026",
    guidelines: [
      "Tích hợp dữ liệu từ các chuyến khảo sát thực địa chung trên các tàu nghiên cứu khoa học biển.",
    ],
  },
  {
    id: "op09",
    code: "OPP-2026-CORAL",
    title: "Giám sát rạn san hô và đa dạng sinh học tầng đáy bằng ảnh độ phân giải cao",
    field: "Sinh học biển",
    closes: "18/09/2026",
    state: "CLOSED",
    summary: "Áp dụng kỹ thuật chụp ảnh lập thể và thị giác máy tính đánh giá độ che phủ rạn san hô tự nhiên.",
    scope: "Khu bảo tồn biển và Viện nghiên cứu sinh thái",
    objective: "Xây dựng bộ dữ liệu hình ảnh mẫu và quy trình tự động nhận dạng các loài sinh vật đáy chỉ thị.",
    topics: ["Sinh học biển", "Phân loại học hình ảnh", "Đa dạng sinh học"],
    relatedExpertIds: ["exp-vn-03", "exp-ru-03", "exp-vn-12", "exp-ru-12"],
    eligiblePartners: "Viện Hải dương học hai nước và các trạm nghiên cứu biển ven bờ.",
    publishedAt: "10/04/2026",
    guidelines: [
      "Đợt nộp hồ sơ đã kết thúc; các đề xuất hợp lệ đã được chuyển sang giai đoạn phản biện chuyên gia.",
    ],
  },
  {
    id: "op10",
    code: "OPP-2026-OCEAN",
    title: "Đồng bộ chuỗi quan trắc hải dương học ven bờ và hải lưu nhiệt đới",
    field: "Hải dương học",
    closes: "15/12/2025",
    state: "CLOSED",
    summary: "Đồng bộ hóa các trạm đo phao ngầm và đối chiếu dữ liệu hải lưu giữa hai phân viện nghiên cứu biển.",
    scope: "Chương trình nghiên cứu trọng điểm hải dương học",
    objective: "Tạo lập bộ số liệu đối chiếu chuẩn xác cho mô hình hoàn lưu đại dương khu vực chuyển tiếp nhiệt đới - ôn đới.",
    topics: ["Hải dương học", "Quan trắc trạm phao", "Hải lưu nhiệt đới"],
    relatedExpertIds: ["exp-vn-08", "exp-ru-08", "exp-vn-12", "exp-ru-12"],
    eligiblePartners: "Viện Hải dương học VAST và Phân viện Viễn Đông Viện Hàn lâm Khoa học Nga.",
    publishedAt: "01/01/2025",
    guidelines: [
      "Dự án đã được phê duyệt và đang vận hành trong giai đoạn triển khai thực địa năm 2026.",
    ],
  },
  {
    id: "op11",
    code: "OPP-2026-QUANTUM",
    title: "Cảm biến từ trường lượng tử phục vụ khảo sát từ tính đáy biển",
    field: "Vật lý lượng tử · Cảm biến",
    closes: "30/11/2026",
    state: "DRAFT",
    summary: "Nghiên cứu nguyên lý cảm biến từ kế nguyên tử quang học phục vụ thăm dò dị thường từ tính tầng nông đáy biển.",
    scope: "Viện Vật lý và Phòng thí nghiệm Quang lượng tử",
    objective: "Thử nghiệm cấu trúc đầu đo từ kế có độ nhạy cao trong môi trường nhiễu điện từ bờ biển.",
    topics: ["Cảm biến lượng tử", "Từ kế", "Địa vật lý"],
    relatedExpertIds: ["exp-vn-01", "exp-ru-02", "exp-vn-11"],
    eligiblePartners: "Các phòng thí nghiệm quang lượng tử và địa vật lý hai nước.",
    guidelines: [
      "Bản thảo hướng dẫn đang trong quá trình lấy ý kiến chuyên môn của ban điều phối.",
    ],
  },
  {
    id: "op12",
    code: "OPP-2026-HYDROGEN",
    title: "Vật liệu xúc tác điện hóa cho sản xuất hydro xanh từ nước biển",
    field: "Năng lượng sạch · Vật liệu",
    closes: "08/11/2026",
    state: "PUBLISHED",
    summary: "Phát triển điện cực màng nano chống kết tủa muối và ức chế ăn mòn clo trong quá trình điện phân nước biển trực tiếp.",
    scope: "Khoa Hóa học và Vật liệu Năng lượng",
    objective: "Tổng hợp các chất xúc tác điện hóa không dùng kim loại quý có độ bền hoạt động cao trong nước biển.",
    topics: ["Hydro xanh", "Xúc tác điện hóa", "Vật liệu mới"],
    relatedExpertIds: ["exp-vn-01", "exp-ru-01", "exp-vn-07", "exp-ru-07"],
    eligiblePartners: "Viện Hóa học, Viện Khoa học Vật liệu và các trường đại học kỹ thuật.",
    publishedAt: "01/08/2026",
    guidelines: [
      "Yêu cầu báo cáo dữ liệu đường cong phân cực và thử nghiệm độ ổn định điện thế tối thiểu 500 giờ liên tục.",
    ],
  },
  {
    id: "op13",
    code: "OPP-2026-CYBER",
    title: "An toàn dữ liệu và mạng lưới cảm biến môi trường phân tán",
    field: "An ninh mạng · IoT biển",
    closes: "22/11/2026",
    state: "DRAFT",
    summary: "Xây dựng giao thức truyền tin tin cậy và mã hóa nhẹ cho các trạm quan trắc hải dương phân tán qua kết nối vệ tinh.",
    scope: "Viện Công nghệ Thông tin và Viễn thông",
    objective: "Bảo đảm tính toàn vẹn và xác thực nguồn dữ liệu từ các phao trôi dạt tự do trên biển.",
    topics: ["IoT biển", "An toàn dữ liệu", "Mã hóa nhẹ"],
    relatedExpertIds: ["exp-vn-04", "exp-ru-04"],
    eligiblePartners: "Khoa An toàn Thông tin và các trung tâm nghiên cứu mạng cảm biến.",
    guidelines: [
      "Đang hoàn thiện tiêu chí đánh giá về mức tiêu thụ năng lượng và băng thông truyền tin vệ tinh.",
    ],
  },
  {
    id: "op14",
    code: "OPP-2026-AGRI",
    title: "Công nghệ sinh học cải tiến giống cây trồng chịu mặn vùng ven biển",
    field: "Nông nghiệp · Sinh học",
    closes: "14/12/2026",
    state: "PUBLISHED",
    summary: "Sử dụng dấu chỉ thị phân tử và chỉnh sửa hệ gen nghiên cứu các gen chống chịu mặn thích ứng vùng nhiễm mặn nhiệt đới.",
    scope: "Viện Di truyền Nông nghiệp và Viện Sinh học Biễn",
    objective: "Xác định các dòng giống có khả năng sinh trưởng tốt tại vùng đất cát ven biển thường xuyên ngập mặn.",
    topics: ["Công nghệ sinh học", "Chịu mặn", "Di truyền thực vật"],
    relatedExpertIds: ["exp-vn-13", "exp-ru-13"],
    eligiblePartners: "Viện Di truyền Nông nghiệp, Học viện Nông nghiệp và Viện Sinh học Thực nghiệm RAS.",
    publishedAt: "12/08/2026",
    guidelines: [
      "Quy trình thử nghiệm phải được tiến hành trong nhà kính kiểm soát trước khi khảo nghiệm diện hẹp ngoài trời.",
    ],
  },
];

export function getOpportunityById(id: string): DetailedOpportunity | undefined {
  return DEMO_OPPORTUNITIES.find((item) => item.id === id || item.code === id);
}

export function getOpportunitiesByState(state: Opportunity["state"]): DetailedOpportunity[] {
  return DEMO_OPPORTUNITIES.filter((item) => item.state === state);
}
