export type Organization = {
  id: string;
  code: string;
  shortName: string;
  fullName: string;
  country: "VN" | "RU";
  city: string;
  address: string;
  website: string;
  type: "ACADEMY" | "UNIVERSITY" | "INSTITUTE" | "ENTERPRISE";
  keyCapabilities: string[];
  leadContacts: string[];
  activeProposalsCount: number;
  activeProjectsCount: number;
  facilitiesSummary: string;
  verified: boolean;
};

export const DEMO_ORGANIZATIONS: Organization[] = [
  {
    id: "org-vn-01",
    code: "VAST",
    shortName: "VAST",
    fullName: "Viện Hàn lâm Khoa học và Công nghệ Việt Nam",
    country: "VN",
    city: "Hà Nội",
    address: "18 Hoàng Quốc Việt, Cầu Giấy, Hà Nội",
    website: "https://vast.gov.vn",
    type: "ACADEMY",
    keyCapabilities: ["Vật liệu mới", "Công nghệ vũ trụ", "Công nghệ sinh học", "Hóa lý bề mặt"],
    leadContacts: ["GS.TS Trần Đình Nam", "PGS.TS Lê Thị Mai"],
    activeProposalsCount: 6,
    activeProjectsCount: 4,
    facilitiesSummary: "Trung tâm đo kiểm phân tích bề mặt nano, hệ thống kính hiển vi điện tử quét SEM/TEM, phòng thử nghiệm gia tốc.",
    verified: true,
  },
  {
    id: "org-vn-02",
    code: "IO-VAST",
    shortName: "IO VAST",
    fullName: "Viện Hải dương học (thuộc VAST)",
    country: "VN",
    city: "Nha Trang",
    address: "01 Cầu Đá, TP. Nha Trang, Khánh Hòa",
    website: "http://www.vnio.org.vn",
    type: "INSTITUTE",
    keyCapabilities: ["Hải dương học", "Sinh học biển", "Khảo sát đáy biển", "Đo đạc hải lưu"],
    leadContacts: ["TS Đỗ Hùng", "TS Trần Hải"],
    activeProposalsCount: 4,
    activeProjectsCount: 3,
    facilitiesSummary: "Tàu nghiên cứu biển ven bờ, bảo tàng mẫu vật hải dương học quốc gia, trạm quan trắc ven bờ Hòn Mun.",
    verified: true,
  },
  {
    id: "org-vn-03",
    code: "VNU-HN",
    shortName: "VNU",
    fullName: "Đại học Quốc gia Hà Nội",
    country: "VN",
    city: "Hà Nội",
    address: "144 Xuân Thủy, Cầu Giấy, Hà Nội",
    website: "https://vnu.edu.vn",
    type: "UNIVERSITY",
    keyCapabilities: ["Khoa học dữ liệu", "Địa mạo ven biển", "Cảm biến hóa sinh", "Trí tuệ nhân tạo"],
    leadContacts: ["PGS.TS Phạm Sơn", "TS Bùi Thu", "TS Lương Hà"],
    activeProposalsCount: 5,
    activeProjectsCount: 3,
    facilitiesSummary: "Cụm máy chủ tính toán hiệu năng cao HPC, phòng thí nghiệm trọng điểm công nghệ phân tích dữ liệu mở.",
    verified: true,
  },
  {
    id: "org-vn-04",
    code: "HUST",
    shortName: "HUST",
    fullName: "Đại học Bách Khoa Hà Nội",
    country: "VN",
    city: "Hà Nội",
    address: "01 Đại Cồ Việt, Hai Bà Trưng, Hà Nội",
    website: "https://hust.edu.vn",
    type: "UNIVERSITY",
    keyCapabilities: ["Robot biển", "Cơ điện tử", "Điều khiển tự động", "Chế tạo cơ khí chính xác"],
    leadContacts: ["TS Đặng Quốc", "PGS.TS Vũ Tuấn"],
    activeProposalsCount: 3,
    activeProjectsCount: 2,
    facilitiesSummary: "Bể thử thủy động lực học mini, xưởng gia công cơ khí chính xác CNC 5 trục, phòng lab điều khiển nhúng.",
    verified: true,
  },
  {
    id: "org-vn-05",
    code: "HCMUT",
    shortName: "HCMUT",
    fullName: "Đại học Bách Khoa - ĐHQG TP.HCM",
    country: "VN",
    city: "TP. Hồ Chí Minh",
    address: "268 Lý Thường Kiệt, Quận 10, TP. HCM",
    website: "https://hcmut.edu.vn",
    type: "UNIVERSITY",
    keyCapabilities: ["Năng lượng biển", "Vật liệu composite", "Kỹ thuật công trình thủy", "Năng lượng tái tạo"],
    leadContacts: ["TS Vũ Linh", "GS.TS Nguyễn Văn Long"],
    activeProposalsCount: 3,
    activeProjectsCount: 2,
    facilitiesSummary: "Kênh tạo sóng nhân tạo, dàn thử nghiệm chuyển đổi năng lượng sóng biển quy mô mô hình.",
    verified: true,
  },
  {
    id: "org-vn-06",
    code: "NEU",
    shortName: "NEU",
    fullName: "Đại học Kinh tế Quốc dân",
    country: "VN",
    city: "Hà Nội",
    address: "207 Giải Phóng, Hai Bà Trưng, Hà Nội",
    website: "https://neu.edu.vn",
    type: "UNIVERSITY",
    keyCapabilities: ["Kinh tế môi trường", "Đô thị ven biển", "Đánh giá rủi ro khí hậu", "Mô hình hóa không gian"],
    leadContacts: ["TS Nguyễn Thảo"],
    activeProposalsCount: 2,
    activeProjectsCount: 1,
    facilitiesSummary: "Trung tâm dữ liệu kinh tế lượng không gian và hệ thống GIS đánh giá rủi ro thiên tai.",
    verified: true,
  },
  {
    id: "org-vn-07",
    code: "VIGMR",
    shortName: "VIGMR",
    fullName: "Viện Khoa học Địa chất và Khoáng sản",
    country: "VN",
    city: "Hà Nội",
    address: "Km9 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    website: "http://vigmr.vn",
    type: "INSTITUTE",
    keyCapabilities: ["Địa chất biển", "Khoáng sản đáy", "Địa vật lý", "Bản đồ kiến tạo"],
    leadContacts: ["TS Hoàng Long"],
    activeProposalsCount: 2,
    activeProjectsCount: 1,
    facilitiesSummary: "Thiết bị đo địa chấn nông phân giải cao, hệ thống phân tích thạch học và khoáng vật biển.",
    verified: true,
  },
  {
    id: "org-vn-08",
    code: "VKIST",
    shortName: "VKIST",
    fullName: "Viện Khoa học & Công nghệ Việt Nam - Hàn Quốc",
    country: "VN",
    city: "Hà Nội",
    address: "Khu Công nghệ cao Hòa Lạc, Thạch Thất, Hà Nội",
    website: "https://vkist.gov.vn",
    type: "INSTITUTE",
    keyCapabilities: ["Công nghệ sinh học", "Hợp chất thiên nhiên", "Y dược biển", "Chiết xuất dược liệu"],
    leadContacts: ["TS Vũ Kim Dung"],
    activeProposalsCount: 2,
    activeProjectsCount: 1,
    facilitiesSummary: "Hệ thống sắc ký lỏng khối phổ chuẩn đoán LC-MS/MS, phòng sạch nuôi cấy tế bào đạt chuẩn GMP.",
    verified: true,
  },
  {
    id: "org-ru-00",
    code: "FONDRUZHBA",
    shortName: "Quỹ Truyền thống & Hữu nghị",
    fullName: "Quỹ Truyền thống và Hữu nghị (Фонд «Традиции и дружба»)",
    country: "RU",
    city: "Moskva",
    address: "125047, Moskva, Đường Tverskaya-Yamskaya số 1, Tòa nhà 30, Văn phòng 01B, Liên bang Nga",
    website: "https://fonddruzhba.ru",
    type: "ENTERPRISE",
    keyCapabilities: ["Điều phối khoa học", "Giao lưu học thuật", "Tài trợ nghiên cứu song phương", "Hợp tác Nga – Việt"],
    leadContacts: ["Đại diện Quỹ Truyền thống và Hữu nghị (info@fonddruzhba.ru)"],
    activeProposalsCount: 8,
    activeProjectsCount: 6,
    facilitiesSummary: "Văn phòng điều phối hợp tác khoa học – công nghệ và đối ngoại học thuật Liên bang Nga – Việt Nam.",
    verified: true,
  },
  {
    id: "org-ru-01",
    code: "FEB-RAS",
    shortName: "FEB RAS",
    fullName: "Phân viện Viễn Đông - Viện Hàn lâm Khoa học Nga",
    country: "RU",
    city: "Vladivostok",
    address: "50 Svetlanskaya St, Vladivostok, 690091",
    website: "http://febras.ru",
    type: "ACADEMY",
    keyCapabilities: ["Hải dương học", "Vật liệu biển", "Sinh học biển sâu", "Khoáng sản đại dương"],
    leadContacts: ["Prof. Alexei Morozov", "Dr. Pavel Sidorov", "Dr. Maria Orlova"],
    activeProposalsCount: 7,
    activeProjectsCount: 5,
    facilitiesSummary: "Đội tàu nghiên cứu khoa học biển Viện sĩ Oparin và Viện sĩ Lavrentyev, trạm nghiên cứu biển Vostok.",
    verified: true,
  },
  {
    id: "org-ru-02",
    code: "MISIS",
    shortName: "MISIS",
    fullName: "Đại học Khoa học và Công nghệ Quốc gia MISIS",
    country: "RU",
    city: "Moskva",
    address: "4 Leninsky Prospekt, Moscow, 119049",
    website: "https://misis.ru",
    type: "UNIVERSITY",
    keyCapabilities: ["Vật liệu nano", "Hợp kim chịu ăn mòn", "Cảm biến", "Địa tin học"],
    leadContacts: ["Prof. Elena Kurchatova", "Dr. Ivan Morozov", "Dr. Olga Smirnova"],
    activeProposalsCount: 6,
    activeProjectsCount: 4,
    facilitiesSummary: "Trung tâm vật liệu nano và composite cấu trúc, phòng lab phân tích quang phổ tia X và bề mặt tiên tiến.",
    verified: true,
  },
  {
    id: "org-ru-03",
    code: "POI-RAS",
    shortName: "POI RAS",
    fullName: "Viện Hải dương học V.I. Il'ichev FEB RAS",
    country: "RU",
    city: "Vladivostok",
    address: "43 Baltiyskaya St, Vladivostok, 690041",
    website: "https://poi.dvo.ru",
    type: "INSTITUTE",
    keyCapabilities: ["Sinh thái biển", "Thủy âm học", "Động lực học vịnh", "Khảo sát đáy biển"],
    leadContacts: ["Dr. Anna Volkova", "Dr. Vladimir Chernov"],
    activeProposalsCount: 3,
    activeProjectsCount: 2,
    facilitiesSummary: "Hệ thống sonar quét sườn và đầu dò âm thanh dưới nước đa chùm tia, phòng nuôi cấy vi sinh vật lạnh.",
    verified: true,
  },
  {
    id: "org-ru-04",
    code: "SPBPU",
    shortName: "SPbPU",
    fullName: "Đại học Bách khoa Peter Đại đế St. Petersburg",
    country: "RU",
    city: "St. Petersburg",
    address: "29 Polytechnicheskaya St, St. Petersburg, 195251",
    website: "https://spbstu.ru",
    type: "UNIVERSITY",
    keyCapabilities: ["Robot tự hành", "Mô phỏng thủy động lực", "Cơ điện tử biển", "Vật liệu nhẹ"],
    leadContacts: ["Prof. Alexei Petrov"],
    activeProposalsCount: 3,
    activeProjectsCount: 2,
    facilitiesSummary: "Bể thử kéo thủy lực siêu dài, cụm siêu máy tính tính toán động lực học chất lưu CFD.",
    verified: true,
  },
  {
    id: "org-ru-05",
    code: "MSU",
    shortName: "MSU",
    fullName: "Đại học Tổng hợp Quốc gia Moskva M.V. Lomonosov",
    country: "RU",
    city: "Moskva",
    address: "1 Leninskie Gory, Moscow, 119991",
    website: "https://msu.ru",
    type: "UNIVERSITY",
    keyCapabilities: ["Địa mạo học", "Hải dương học tính toán", "Mô hình hóa số", "Sinh thái học"],
    leadContacts: ["Dr. Sergei Kozlov"],
    activeProposalsCount: 3,
    activeProjectsCount: 2,
    facilitiesSummary: "Kho dữ liệu địa lý toàn cầu, phòng thí nghiệm mô hình động lực bờ biển và xói lở.",
    verified: true,
  },
  {
    id: "org-ru-06",
    code: "FEFU",
    shortName: "FEFU",
    fullName: "Đại học Tổng hợp Liên bang Viễn Đông",
    country: "RU",
    city: "Vladivostok",
    address: "8 Sukhanova St, Vladivostok, 690090",
    website: "https://fefu.ru",
    type: "UNIVERSITY",
    keyCapabilities: ["Năng lượng biển", "Công nghệ dưới nước", "Kỹ thuật công trình biển", "Vật liệu y sinh"],
    leadContacts: ["Dr. Kirill Romanov"],
    activeProposalsCount: 2,
    activeProjectsCount: 2,
    facilitiesSummary: "Trung tâm thử nghiệm thiết bị ngoài khơi trên đảo Russky, phòng thí nghiệm vật liệu năng lượng sinh học.",
    verified: true,
  },
  {
    id: "org-ru-07",
    code: "HSE",
    shortName: "HSE",
    fullName: "Trường Kinh tế Cao cấp Moskva (HSE University)",
    country: "RU",
    city: "Moskva",
    address: "20 Myasnitskaya St, Moscow, 101000",
    website: "https://hse.ru",
    type: "UNIVERSITY",
    keyCapabilities: ["Phân tích không gian", "Kinh tế biến đổi khí hậu", "Quy hoạch đô thị số", "Chính sách khoa học"],
    leadContacts: ["Dr. Irina Belova"],
    activeProposalsCount: 2,
    activeProjectsCount: 1,
    facilitiesSummary: "Viện Phân tích Không gian và Quy hoạch Đô thị, cụm xử lý dữ liệu lớn thống kê môi trường.",
    verified: true,
  },
  {
    id: "org-ru-08",
    code: "GEOKHI-RAS",
    shortName: "GEOKHI RAS",
    fullName: "Viện Địa hóa và Hóa học Phân tích V.I. Vernadsky RAS",
    country: "RU",
    city: "Moskva",
    address: "19 Kosygina St, Moscow, 119991",
    website: "http://geokhi.ru",
    type: "INSTITUTE",
    keyCapabilities: ["Địa chất biển", "Địa hóa học", "Đồng vị phóng xạ", "Khoáng vật biển sâu"],
    leadContacts: ["Dr. Dmitri Levin"],
    activeProposalsCount: 2,
    activeProjectsCount: 1,
    facilitiesSummary: "Máy đo khối phổ ion thứ cấp SIMS, hệ thống phân tích đồng vị chính xác cao phục vụ trầm tích biển.",
    verified: true,
  },
];

export function getOrganizationById(id: string): Organization | undefined {
  return DEMO_ORGANIZATIONS.find((org) => org.id === id || org.code === id);
}

export function getOrganizationsByCountry(country: "VN" | "RU"): Organization[] {
  return DEMO_ORGANIZATIONS.filter((org) => org.country === country);
}
