import type { Project, ProjectState } from "../demo-v2/types";

export type DetailedProject = Project & {
  field?: string;
  leadPi?: string;
  vnOrg?: string;
  ruOrg?: string;
  durationMonths?: number;
  startDate?: string;
  endDate?: string;
  reportIds?: string[];
};

export const DEMO_PROJECTS: DetailedProject[] = [
  {
    id: "pr01",
    proposalId: "p09",
    code: "RU-VN-2025-OCEAN-03",
    title: "Đồng bộ chuỗi quan trắc hải dương học ven bờ",
    partner: "FEB RAS",
    field: "Hải dương học",
    leadPi: "TS Đỗ Hùng",
    vnOrg: "IO VAST",
    ruOrg: "FEB RAS",
    durationMonths: 24,
    startDate: "01/01/2026",
    endDate: "31/12/2027",
    state: "ACTIVE",
    progress: 48,
    next: "Đồng bộ bộ từ điển dữ liệu phiên bản 2 và kết nối trạm phao",
    reportIds: ["rp02"],
    milestones: [
      { id: "m01", title: "Chuẩn hóa cấu trúc dữ liệu quan trắc phao ngầm", due: "15/05/2026", state: "DONE" },
      { id: "m02", title: "Đồng bộ pipeline trao đổi và kiểm tra lỗi thời gian thực", due: "30/09/2026", state: "IN_PROGRESS" },
      { id: "m03", title: "Đối chiếu dữ liệu lịch sử và kiểm chuẩn mô hình", due: "15/12/2026", state: "TODO" },
      { id: "m04", title: "Tổng hợp cơ sở dữ liệu chuỗi thời gian 2 năm", due: "15/11/2027", state: "TODO" },
    ],
  },
  {
    id: "pr02",
    proposalId: "p07",
    code: "RU-VN-2026-BIO-08",
    title: "Độ bền vật liệu sinh học trong điều kiện biển",
    partner: "FEB RAS",
    field: "Vật liệu sinh học",
    leadPi: "PGS.TS Lê Thị Mai",
    vnOrg: "VAST",
    ruOrg: "FEB RAS",
    durationMonths: 36,
    startDate: "01/03/2026",
    endDate: "28/02/2029",
    state: "ACTIVE",
    progress: 75,
    next: "Hoàn tất chuỗi thử nghiệm gia tốc môi trường biển",
    reportIds: ["rp01"],
    milestones: [
      { id: "m05", title: "Thiết lập mẫu chuẩn và màng polymer sinh học", due: "15/05/2026", state: "DONE" },
      { id: "m06", title: "Thử nghiệm gia tốc môi trường biển trong buồng phun sương muối", due: "30/08/2026", state: "IN_PROGRESS" },
      { id: "m07", title: "Đối chiếu dữ liệu ăn mòn VN–RU và phổ XPS bề mặt", due: "20/12/2026", state: "TODO" },
    ],
  },
  {
    id: "pr03",
    proposalId: "p03",
    code: "RU-VN-2026-MAR-02",
    title: "Giám sát đa dạng sinh học biển bằng dữ liệu ảnh",
    partner: "POI RAS",
    field: "Sinh học biển",
    leadPi: "TS Trần Hải",
    vnOrg: "IO VAST",
    ruOrg: "POI RAS",
    durationMonths: 24,
    startDate: "01/10/2026",
    endDate: "30/09/2028",
    state: "PLANNED",
    progress: 8,
    next: "Chờ quyết định chính thức để kích hoạt dự án thực địa",
    reportIds: [],
    milestones: [
      { id: "m08", title: "Khởi động dự án và ký phụ lục làm việc song phương", due: "20/09/2026", state: "TODO" },
      { id: "m09", title: "Chuẩn hóa bộ ảnh mẫu rạn san hô và sinh vật đáy", due: "30/11/2026", state: "TODO" },
    ],
  },
  {
    id: "pr04",
    proposalId: "p04",
    code: "RU-VN-2026-DATA-03",
    title: "Liên thông dữ liệu quan trắc hải dương VN–RU",
    partner: "FEB RAS",
    field: "Dữ liệu khoa học",
    leadPi: "PGS.TS Phạm Sơn",
    vnOrg: "VNU",
    ruOrg: "FEB RAS",
    durationMonths: 24,
    startDate: "01/04/2026",
    endDate: "31/03/2028",
    state: "BLOCKED",
    progress: 31,
    next: "Gỡ chặn quyền truy cập cổng kết nối và chứng chỉ bảo mật máy chủ",
    reportIds: ["rp04"],
    milestones: [
      { id: "m10", title: "Thiết lập không gian dữ liệu dùng chung", due: "20/07/2026", state: "DONE" },
      { id: "m11", title: "Xác minh chứng chỉ bảo mật và phân quyền đối tác", due: "22/08/2026", state: "OVERDUE" },
      { id: "m12", title: "Thử nghiệm tải truyền dữ liệu đồng bộ", due: "30/10/2026", state: "TODO" },
    ],
  },
  {
    id: "pr05",
    proposalId: "p02",
    code: "RU-VN-2026-AI-04",
    title: "AI dự báo sớm tai biến địa chất ven biển",
    partner: "MISIS",
    field: "AI · Địa chất biển",
    leadPi: "TS Nguyễn Minh Anh",
    vnOrg: "VAST",
    ruOrg: "MISIS",
    durationMonths: 18,
    state: "CANCELLED",
    progress: 12,
    next: "Hồ sơ dự án đã đóng lại theo thông báo hủy",
    reportIds: [],
    milestones: [
      { id: "m13", title: "Khảo sát thực địa bước đầu", due: "10/06/2026", state: "DONE" },
      { id: "m14", title: "Bàn giao dữ liệu địa hình số", due: "15/07/2026", state: "OVERDUE" },
    ],
  },
  {
    id: "pr06",
    proposalId: "p11",
    code: "RU-VN-2026-CLIMATE-11",
    title: "Đánh giá rủi ro khí hậu cho đô thị ven biển",
    partner: "HSE",
    field: "Khí hậu",
    leadPi: "TS Nguyễn Thảo",
    vnOrg: "NEU",
    ruOrg: "HSE",
    durationMonths: 12,
    startDate: "01/08/2025",
    endDate: "31/07/2026",
    state: "COMPLETED",
    progress: 100,
    next: "Đã nghiệm thu và hoàn tất bàn giao cơ sở dữ liệu GIS",
    reportIds: ["rp03"],
    milestones: [
      { id: "m15", title: "Khảo sát bảng hỏi tại 3 đô thị thí điểm", due: "30/11/2025", state: "DONE" },
      { id: "m16", title: "Xây dựng bản đồ phân vùng rủi ro ngập lụt", due: "15/04/2026", state: "DONE" },
      { id: "m17", title: "Hoàn thiện báo cáo tổng kết và hội thảo công bố", due: "10/08/2026", state: "DONE" },
    ],
  },
  {
    id: "pr07",
    proposalId: "p21",
    code: "RU-VN-2025-EDDY-21",
    title: "Cấu trúc vi mô và năng lượng xoáy nhiệt đới Tây Thái Bình Dương",
    partner: "FEB RAS",
    field: "Hải dương học",
    leadPi: "TS Đỗ Hùng",
    vnOrg: "IO VAST",
    ruOrg: "FEB RAS",
    durationMonths: 36,
    startDate: "01/02/2026",
    endDate: "31/01/2029",
    state: "ACTIVE",
    progress: 55,
    next: "Phân tích số liệu CTD chuyến tàu Oparin đợt 1",
    reportIds: ["rp05"],
    milestones: [
      { id: "m18", title: "Chuyến khảo sát hải dương liên hợp đợt 1", due: "30/04/2026", state: "DONE" },
      { id: "m19", title: "Xử lý dữ liệu vi cấu trúc xoáy nhiệt đới", due: "15/10/2026", state: "IN_PROGRESS" },
      { id: "m20", title: "Hiệu chỉnh mô hình hoàn lưu khí quyển - đại dương", due: "20/03/2027", state: "TODO" },
    ],
  },
  {
    id: "pr08",
    proposalId: "p08",
    code: "RU-VN-2026-ENERGY-09",
    title: "Tối ưu vật liệu cho năng lượng sóng quy mô nhỏ",
    partner: "FEFU",
    field: "Năng lượng biển",
    leadPi: "TS Vũ Linh",
    vnOrg: "HCMUT",
    ruOrg: "FEFU",
    durationMonths: 24,
    startDate: "01/05/2026",
    endDate: "30/04/2028",
    state: "AT_RISK",
    progress: 20,
    next: "Điều chỉnh kế hoạch thử nghiệm theo khuyến nghị phản biện",
    reportIds: ["rp06"],
    milestones: [
      { id: "m21", title: "Mô phỏng động lực học thiết bị dạng phao", due: "15/07/2026", state: "DONE" },
      { id: "m22", title: "Chế tạo mẫu thử cánh tuabin chuyển đổi", due: "25/08/2026", state: "OVERDUE" },
      { id: "m23", title: "Thử nghiệm kênh sóng nhân tạo", due: "30/11/2026", state: "TODO" },
    ],
  },
  {
    id: "pr09",
    proposalId: "p19",
    code: "RU-VN-2026-QUANTUM-19",
    title: "Từ kế lượng tử quang học thăm dò khoáng sản tầng nông",
    partner: "MISIS",
    field: "Vật lý lượng tử",
    leadPi: "GS.TS Trần Đình Nam",
    vnOrg: "VAST",
    ruOrg: "MISIS",
    durationMonths: 30,
    state: "PLANNED",
    progress: 0,
    next: "Chuẩn bị nhân sự và ký kết thỏa thuận hợp tác đo kiểm quang lượng tử",
    reportIds: [],
    milestones: [
      { id: "m24", title: "Thiết lập buồng cách ly từ trường", due: "15/12/2026", state: "TODO" },
      { id: "m25", title: "Lắp ráp khối đầu dò quang học", due: "15/04/2027", state: "TODO" },
    ],
  },
  {
    id: "pr10",
    proposalId: "p06",
    code: "RU-VN-2026-COAST-06",
    title: "Mô hình số biến động đường bờ khu vực nhiệt đới",
    partner: "MSU",
    field: "Địa mạo ven biển",
    leadPi: "TS Bùi Thu",
    vnOrg: "VNU",
    ruOrg: "MSU",
    durationMonths: 24,
    startDate: "01/06/2026",
    endDate: "31/05/2028",
    state: "ACTIVE",
    progress: 40,
    next: "Thu thập số liệu đo sâu hồi âm tại dải ven biển miền Trung",
    reportIds: ["rp07"],
    milestones: [
      { id: "m26", title: "Thu thập dữ liệu địa hình đáy ven bờ", due: "30/07/2026", state: "DONE" },
      { id: "m27", title: "Cài đặt và hiệu chỉnh mô hình sóng Delft3D", due: "15/11/2026", state: "IN_PROGRESS" },
      { id: "m28", title: "Kiểm chứng kịch bản biến đổi đường bờ 10 năm", due: "30/05/2027", state: "TODO" },
    ],
  },
  {
    id: "pr11",
    proposalId: "p16",
    code: "RU-VN-2026-CYBER-16",
    title: "Mã hóa nhẹ và xác thực dữ liệu cho mạng phao quan trắc",
    partner: "SPbPU",
    field: "An ninh mạng · IoT",
    leadPi: "PGS.TS Phạm Sơn",
    vnOrg: "VNU",
    ruOrg: "SPbPU",
    durationMonths: 18,
    state: "PLANNED",
    progress: 5,
    next: "Chờ phê duyệt cam kết hạ tầng của trường đại học chủ quản",
    reportIds: [],
    milestones: [
      { id: "m29", title: "Xây dựng kiến trúc giao thức truyền tin", due: "15/01/2027", state: "TODO" },
    ],
  },
  {
    id: "pr12",
    proposalId: "p10",
    code: "RU-VN-2026-SENSOR-10",
    title: "Cảm biến hóa học bền môi trường nước mặn",
    partner: "MISIS",
    field: "Cảm biến",
    leadPi: "TS Lương Hà",
    vnOrg: "VNU",
    ruOrg: "MISIS",
    durationMonths: 12,
    state: "CANCELLED",
    progress: 15,
    next: "Dự án đã dừng triển khai theo kết luận của Hội đồng",
    reportIds: [],
    milestones: [
      { id: "m30", title: "Tổng hợp màng nhạy ion kim loại", due: "15/07/2026", state: "DONE" },
    ],
  },
  {
    id: "pr13",
    proposalId: "p17",
    code: "RU-VN-2026-AGRI-17",
    title: "Chỉ thị phân tử sàng lọc giống lúa chịu mặn ven biển",
    partner: "FEB RAS",
    field: "Nông nghiệp · Sinh học",
    leadPi: "TS Vũ Kim Dung",
    vnOrg: "VKIST",
    ruOrg: "FEB RAS",
    durationMonths: 36,
    state: "PLANNED",
    progress: 0,
    next: "Hoàn tất giai đoạn tiếp nhận hồ sơ và phân công thẩm định",
    reportIds: [],
    milestones: [
      { id: "m31", title: "Thu thập nguồn gen bản địa", due: "28/02/2027", state: "TODO" },
    ],
  },
  {
    id: "pr14",
    proposalId: "p20",
    code: "RU-VN-2026-SEDIMENT-20",
    title: "Phân tích địa hóa đồng vị trầm tích bồi tụ cửa sông",
    partner: "GEOKHI RAS",
    field: "Địa chất biển",
    leadPi: "TS Hoàng Long",
    vnOrg: "VIGMR",
    ruOrg: "GEOKHI RAS",
    durationMonths: 24,
    startDate: "01/04/2026",
    endDate: "31/03/2028",
    state: "ACTIVE",
    progress: 35,
    next: "Gửi mẫu trầm tích sang phòng lab GEOKHI RAS để phân tích ICP-MS",
    reportIds: ["rp08"],
    milestones: [
      { id: "m32", title: "Lấy mẫu lõi trầm tích tại 12 vị trí", due: "30/06/2026", state: "DONE" },
      { id: "m33", title: "Phân tích khoáng vật và hàm lượng kim loại nặng", due: "30/10/2026", state: "IN_PROGRESS" },
      { id: "m34", title: "Xây dựng biểu đồ tích tụ trầm tích theo thời gian", due: "28/02/2027", state: "TODO" },
    ],
  },
];

export function getProjectById(id: string): DetailedProject | undefined {
  return DEMO_PROJECTS.find((item) => item.id === id || item.code === id);
}

export function getProjectsByState(state: ProjectState): DetailedProject[] {
  return DEMO_PROJECTS.filter((item) => item.state === state);
}
