import type { Proposal, ProposalState } from "../demo-v2/types";

export type DetailedProposal = Proposal & {
  opportunityId?: string;
  vnOrgId: string;
  ruOrgId: string;
  vnPiId: string;
  ruPiId: string;
  endorsementId?: string;
  reviewAssignmentIds?: string[];
  decisionId?: string;
  projectId?: string;
};

export const DEMO_PROPOSALS: DetailedProposal[] = [
  {
    id: "p01",
    code: "RU-VN-2026-NANO-01",
    title: "Vật liệu nano-composite chịu ăn mòn biển nhiệt đới",
    field: "Vật liệu mới",
    vnOrg: "VAST",
    ruOrg: "FEB RAS",
    vnPi: "PGS.TS Lê Thị Mai",
    ruPi: "Prof. Elena Kurchatova",
    state: "WAITING_PARTNER",
    deadline: "30/08/2026",
    updatedAt: "24/08/2026 17:32",
    readiness: 62,
    missing: ["Xác nhận đồng chủ nhiệm phía Nga"],
    note: "Đang chờ PGS.TS Kurchatova gửi văn bản xác nhận chữ ký số của đơn vị chủ quản phía Nga.",
    opportunityId: "op01",
    vnOrgId: "org-vn-01",
    ruOrgId: "org-ru-01",
    vnPiId: "exp-vn-01",
    ruPiId: "exp-ru-01",
    endorsementId: "en05",
    reviewAssignmentIds: ["rv08"],
  },
  {
    id: "p02",
    code: "RU-VN-2026-AI-04",
    title: "AI dự báo sớm tai biến địa chất ven biển",
    field: "AI · Địa chất biển",
    vnOrg: "VAST",
    ruOrg: "MISIS",
    vnPi: "TS Nguyễn Minh Anh",
    ruPi: "Dr. Ivan Morozov",
    state: "NEEDS_INFO",
    deadline: "25/08/2026",
    updatedAt: "24/08/2026 16:20",
    readiness: 78,
    missing: ["Nguồn dữ liệu dùng chung", "Phạm vi thử nghiệm"],
    note: "Điều phối yêu cầu bổ sung minh chứng dữ liệu dùng chung trước khi tiếp tục sàng lọc.",
    opportunityId: "op02",
    vnOrgId: "org-vn-01",
    ruOrgId: "org-ru-02",
    vnPiId: "exp-vn-02",
    ruPiId: "exp-ru-02",
    endorsementId: "en02",
    projectId: "pr05",
  },
  {
    id: "p03",
    code: "RU-VN-2026-MAR-02",
    title: "Giám sát đa dạng sinh học biển bằng dữ liệu ảnh",
    field: "Sinh học biển",
    vnOrg: "IO VAST",
    ruOrg: "POI RAS",
    vnPi: "TS Trần Hải",
    ruPi: "Dr. Anna Volkova",
    state: "ELIGIBLE",
    deadline: "18/09/2026",
    updatedAt: "24/08/2026 14:05",
    readiness: 100,
    note: "Hồ sơ đã qua sàng lọc thành công, sẵn sàng phân công chuyên gia phản biện.",
    opportunityId: "op09",
    vnOrgId: "org-vn-02",
    ruOrgId: "org-ru-03",
    vnPiId: "exp-vn-03",
    ruPiId: "exp-ru-03",
    endorsementId: "en03",
    reviewAssignmentIds: ["rv03"],
    projectId: "pr03",
  },
  {
    id: "p04",
    code: "RU-VN-2026-DATA-03",
    title: "Liên thông dữ liệu quan trắc hải dương VN–RU",
    field: "Dữ liệu khoa học",
    vnOrg: "VNU",
    ruOrg: "FEB RAS",
    vnPi: "PGS.TS Phạm Sơn",
    ruPi: "Dr. Pavel Sidorov",
    state: "SUBMITTED",
    deadline: "02/09/2026",
    updatedAt: "24/08/2026 12:10",
    readiness: 96,
    note: "Đã nộp vào hàng đợi điều phối viên, chờ kiểm tra điều kiện hình thức.",
    opportunityId: "op03",
    vnOrgId: "org-vn-03",
    ruOrgId: "org-ru-01",
    vnPiId: "exp-vn-04",
    ruPiId: "exp-ru-04",
    endorsementId: "en06",
    reviewAssignmentIds: ["rv04"],
    projectId: "pr04",
  },
  {
    id: "p05",
    code: "RU-VN-2026-ROBOT-05",
    title: "Robot tự hành khảo sát vùng nước nông",
    field: "Robot biển",
    vnOrg: "HUST",
    ruOrg: "SPbPU",
    vnPi: "TS Đặng Quốc",
    ruPi: "Prof. Alexei Petrov",
    state: "NOT_ELIGIBLE",
    deadline: "19/08/2026",
    updatedAt: "23/08/2026 11:40",
    readiness: 71,
    missing: ["Phạm vi đối tác chưa đáp ứng điều kiện chương trình"],
    note: "Không đáp ứng tiêu chí tỷ lệ cơ sở hạ tầng tham gia theo quy định hợp tác đợt 2026.",
    opportunityId: "op05",
    vnOrgId: "org-vn-04",
    ruOrgId: "org-ru-04",
    vnPiId: "exp-vn-05",
    ruPiId: "exp-ru-05",
    endorsementId: "en04",
    reviewAssignmentIds: ["rv07"],
  },
  {
    id: "p06",
    code: "RU-VN-2026-COAST-06",
    title: "Mô hình số biến động đường bờ khu vực nhiệt đới",
    field: "Địa mạo ven biển",
    vnOrg: "VNU",
    ruOrg: "MSU",
    vnPi: "TS Bùi Thu",
    ruPi: "Dr. Sergei Kozlov",
    state: "IN_REVIEW",
    deadline: "05/09/2026",
    updatedAt: "23/08/2026 09:18",
    readiness: 100,
    note: "Hội đồng chuyên môn đang thực hiện đánh giá theo rubric đa tiêu chí.",
    opportunityId: "op04",
    vnOrgId: "org-vn-03",
    ruOrgId: "org-ru-05",
    vnPiId: "exp-vn-06",
    ruPiId: "exp-ru-06",
    endorsementId: "en07",
    reviewAssignmentIds: ["rv02"],
  },
  {
    id: "p07",
    code: "RU-VN-2026-BIO-08",
    title: "Độ bền vật liệu sinh học trong điều kiện biển",
    field: "Vật liệu sinh học",
    vnOrg: "VAST",
    ruOrg: "FEB RAS",
    vnPi: "PGS.TS Lê Thị Mai",
    ruPi: "Prof. Elena Kurchatova",
    state: "IN_REVIEW",
    deadline: "30/08/2026",
    updatedAt: "22/08/2026 15:45",
    readiness: 100,
    note: "Chuyên gia phản biện đã lưu bản nháp đánh giá 8.45/10.",
    opportunityId: "op01",
    vnOrgId: "org-vn-01",
    ruOrgId: "org-ru-01",
    vnPiId: "exp-vn-01",
    ruPiId: "exp-ru-01",
    endorsementId: "en08",
    reviewAssignmentIds: ["rv01"],
    decisionId: "dc04",
    projectId: "pr02",
  },
  {
    id: "p08",
    code: "RU-VN-2026-ENERGY-09",
    title: "Tối ưu vật liệu cho năng lượng sóng quy mô nhỏ",
    field: "Năng lượng biển",
    vnOrg: "HCMUT",
    ruOrg: "FEFU",
    vnPi: "TS Vũ Linh",
    ruPi: "Dr. Kirill Romanov",
    state: "REVISION",
    deadline: "28/08/2026",
    updatedAt: "22/08/2026 13:11",
    readiness: 88,
    missing: ["Điều chỉnh mục tiêu nghiên cứu theo ý kiến phản biện"],
    note: "Cơ quan quyết định yêu cầu nhóm nghiên cứu thu hẹp phạm vi thử nghiệm sang quy mô phòng lab.",
    opportunityId: "op07",
    vnOrgId: "org-vn-05",
    ruOrgId: "org-ru-06",
    vnPiId: "exp-vn-07",
    ruPiId: "exp-ru-07",
    endorsementId: "en09",
    reviewAssignmentIds: ["rv05"],
    decisionId: "dc01",
  },
  {
    id: "p09",
    code: "RU-VN-2025-OCEAN-03",
    title: "Đồng bộ chuỗi quan trắc hải dương học ven bờ",
    field: "Hải dương học",
    vnOrg: "IO VAST",
    ruOrg: "FEB RAS",
    vnPi: "TS Đỗ Hùng",
    ruPi: "Dr. Maria Orlova",
    state: "APPROVED",
    deadline: "15/12/2025",
    updatedAt: "20/08/2026 08:30",
    readiness: 100,
    note: "Đã có quyết định phê duyệt chính thức, dự án đang triển khai các mốc kỹ thuật.",
    opportunityId: "op10",
    vnOrgId: "org-vn-02",
    ruOrgId: "org-ru-01",
    vnPiId: "exp-vn-08",
    ruPiId: "exp-ru-08",
    endorsementId: "en10",
    decisionId: "dc02",
    projectId: "pr01",
  },
  {
    id: "p10",
    code: "RU-VN-2026-SENSOR-10",
    title: "Cảm biến hóa học bền môi trường nước mặn",
    field: "Cảm biến",
    vnOrg: "VNU",
    ruOrg: "MISIS",
    vnPi: "TS Lương Hà",
    ruPi: "Dr. Olga Smirnova",
    state: "REJECTED",
    deadline: "12/08/2026",
    updatedAt: "18/08/2026 17:22",
    readiness: 100,
    note: "Hồ sơ không được chấp thuận do tính khả thi trong điều kiện thực địa chưa đạt ngưỡng yêu cầu.",
    opportunityId: "op01",
    vnOrgId: "org-vn-03",
    ruOrgId: "org-ru-02",
    vnPiId: "exp-vn-09",
    ruPiId: "exp-ru-09",
    endorsementId: "en11",
    reviewAssignmentIds: ["rv06"],
    decisionId: "dc03",
  },
  {
    id: "p11",
    code: "RU-VN-2026-CLIMATE-11",
    title: "Đánh giá rủi ro khí hậu cho đô thị ven biển",
    field: "Khí hậu",
    vnOrg: "NEU",
    ruOrg: "HSE",
    vnPi: "TS Nguyễn Thảo",
    ruPi: "Dr. Irina Belova",
    state: "WAITING_ORG_CONFIRMATION",
    deadline: "01/09/2026",
    updatedAt: "24/08/2026 10:05",
    readiness: 84,
    missing: ["Xác nhận của tổ chức phía Việt Nam"],
    note: "Đang chờ đại diện Viện Nghiên cứu Đô thị NEU ký điện tử xác nhận cam kết hạ tầng GIS.",
    opportunityId: "op04",
    vnOrgId: "org-vn-06",
    ruOrgId: "org-ru-07",
    vnPiId: "exp-vn-10",
    ruPiId: "exp-ru-10",
    endorsementId: "en01",
    projectId: "pr06",
  },
  {
    id: "p12",
    code: "RU-VN-2026-GEO-12",
    title: "Cơ sở dữ liệu địa chất biển song phương",
    field: "Địa chất biển",
    vnOrg: "VIGMR",
    ruOrg: "GEOKHI RAS",
    vnPi: "TS Hoàng Long",
    ruPi: "Dr. Dmitri Levin",
    state: "CANCELLED",
    deadline: "10/09/2026",
    updatedAt: "21/08/2026 14:40",
    readiness: 44,
    note: "Nhóm nghiên cứu chủ động thu hồi bản nháp để hoàn thiện lại thỏa thuận bản quyền dữ liệu địa chấn.",
    opportunityId: "op08",
    vnOrgId: "org-vn-07",
    ruOrgId: "org-ru-08",
    vnPiId: "exp-vn-11",
    ruPiId: "exp-ru-11",
    endorsementId: "en12",
  },
  {
    id: "p13",
    code: "RU-VN-2026-BIO-13",
    title: "Chiết xuất hoạt chất sinh học biển từ hải miên nhiệt đới",
    field: "Công nghệ sinh học",
    vnOrg: "VKIST",
    ruOrg: "FEB RAS",
    vnPi: "TS Vũ Kim Dung",
    ruPi: "Dr. Tatyana Gerasimova",
    state: "DRAFT",
    deadline: "25/10/2026",
    updatedAt: "24/08/2026 11:20",
    readiness: 35,
    missing: ["Thuyết minh đề cương chi tiết", "Danh mục trang thiết bị dùng chung"],
    note: "Đang biên soạn đề cương phần chiết xuất hoạt chất và quy chuẩn phân tích sắc ký khối phổ.",
    opportunityId: "op06",
    vnOrgId: "org-vn-08",
    ruOrgId: "org-ru-01",
    vnPiId: "exp-vn-13",
    ruPiId: "exp-ru-13",
  },
  {
    id: "p14",
    code: "RU-VN-2026-HYDRO-14",
    title: "Điện cực nano xúc tác sản xuất hydro từ nước biển trực tiếp",
    field: "Năng lượng sạch",
    vnOrg: "VAST",
    ruOrg: "MISIS",
    vnPi: "PGS.TS Lê Thị Mai",
    ruPi: "Prof. Elena Kurchatova",
    state: "DRAFT",
    deadline: "08/11/2026",
    updatedAt: "23/08/2026 16:50",
    readiness: 42,
    missing: ["Bản thiết kế mô hình bình điện phân mẫu"],
    note: "Đang thảo luận cấu trúc lớp phủ chống ăn mòn ion clorua cho cực dương.",
    opportunityId: "op12",
    vnOrgId: "org-vn-01",
    ruOrgId: "org-ru-02",
    vnPiId: "exp-vn-01",
    ruPiId: "exp-ru-01",
  },
  {
    id: "p15",
    code: "RU-VN-2026-WAVE-15",
    title: "Thiết bị thu hồi năng lượng sóng dạng phao dao động ven đảo",
    field: "Năng lượng biển",
    vnOrg: "HCMUT",
    ruOrg: "FEFU",
    vnPi: "TS Vũ Linh",
    ruPi: "Dr. Kirill Romanov",
    state: "WAITING_PARTNER",
    deadline: "12/10/2026",
    updatedAt: "24/08/2026 09:15",
    readiness: 58,
    missing: ["Kế hoạch thử nghiệm thực tế tại vùng biển Viễn Đông"],
    note: "Chờ phía FEFU gửi phương án thử nghiệm đo kiểm tại trạm đảo Russky.",
    opportunityId: "op07",
    vnOrgId: "org-vn-05",
    ruOrgId: "org-ru-06",
    vnPiId: "exp-vn-07",
    ruPiId: "exp-ru-07",
  },
  {
    id: "p16",
    code: "RU-VN-2026-CYBER-16",
    title: "Mã hóa nhẹ và xác thực dữ liệu cho mạng phao quan trắc",
    field: "An ninh mạng · IoT",
    vnOrg: "VNU",
    ruOrg: "SPbPU",
    vnPi: "PGS.TS Phạm Sơn",
    ruPi: "Prof. Alexei Petrov",
    state: "WAITING_ORG_CONFIRMATION",
    deadline: "22/11/2026",
    updatedAt: "23/08/2026 14:10",
    readiness: 81,
    missing: ["Cam kết hỗ trợ hạ tầng trắc nghiệm an toàn mạng"],
    note: "Đang chờ Ban Giám hiệu ĐHQG Hà Nội phê duyệt cam kết bảo mật hạ tầng mạng IoT thí điểm.",
    opportunityId: "op13",
    vnOrgId: "org-vn-03",
    ruOrgId: "org-ru-04",
    vnPiId: "exp-vn-04",
    ruPiId: "exp-ru-05",
    endorsementId: "en13",
  },
  {
    id: "p17",
    code: "RU-VN-2026-AGRI-17",
    title: "Chỉ thị phân tử sàng lọc giống lúa chịu mặn thích ứng ven biển",
    field: "Nông nghiệp · Sinh học",
    vnOrg: "VKIST",
    ruOrg: "FEB RAS",
    vnPi: "TS Vũ Kim Dung",
    ruPi: "Dr. Tatyana Gerasimova",
    state: "SUBMITTED",
    deadline: "14/12/2026",
    updatedAt: "24/08/2026 15:30",
    readiness: 94,
    note: "Hồ sơ vừa nộp, đang chờ phân công điều phối viên thẩm định sơ bộ.",
    opportunityId: "op14",
    vnOrgId: "org-vn-08",
    ruOrgId: "org-ru-01",
    vnPiId: "exp-vn-13",
    ruPiId: "exp-ru-13",
    endorsementId: "en14",
  },
  {
    id: "p18",
    code: "RU-VN-2026-CORAL-18",
    title: "Nhận dạng tự động biến động rạn san hô bằng AI và camera đáy",
    field: "Sinh học biển · AI",
    vnOrg: "IO VAST",
    ruOrg: "POI RAS",
    vnPi: "TS Trần Hải",
    ruPi: "Dr. Anna Volkova",
    state: "NEEDS_INFO",
    deadline: "25/08/2026",
    updatedAt: "24/08/2026 13:45",
    readiness: 76,
    missing: ["Phương án xử lý dữ liệu ảnh độ phân giải siêu cao trong điều kiện nước đục"],
    note: "Điều phối viên đề nghị làm rõ độ chính xác thuật toán phân loại trong mùa mưa lũ.",
    opportunityId: "op09",
    vnOrgId: "org-vn-02",
    ruOrgId: "org-ru-03",
    vnPiId: "exp-vn-03",
    ruPiId: "exp-ru-03",
    endorsementId: "en15",
  },
  {
    id: "p19",
    code: "RU-VN-2026-QUANTUM-19",
    title: "Từ kế lượng tử quang học thăm dò khoáng sản tầng nông đáy biển",
    field: "Vật lý lượng tử",
    vnOrg: "VAST",
    ruOrg: "MISIS",
    vnPi: "GS.TS Trần Đình Nam",
    ruPi: "Dr. Ivan Morozov",
    state: "ELIGIBLE",
    deadline: "30/11/2026",
    updatedAt: "24/08/2026 14:50",
    readiness: 100,
    note: "Hồ sơ đạt yêu cầu sàng lọc, chuyển sang ban thư ký điều phối reviewer.",
    opportunityId: "op11",
    vnOrgId: "org-vn-01",
    ruOrgId: "org-ru-02",
    vnPiId: "exp-vn-12",
    ruPiId: "exp-ru-02",
    endorsementId: "en16",
    reviewAssignmentIds: ["rv09"],
  },
  {
    id: "p20",
    code: "RU-VN-2026-SEDIMENT-20",
    title: "Phân tích địa hóa đồng vị trầm tích bồi tụ vùng cửa sông",
    field: "Địa chất biển",
    vnOrg: "VIGMR",
    ruOrg: "GEOKHI RAS",
    vnPi: "TS Hoàng Long",
    ruPi: "Dr. Dmitri Levin",
    state: "REVISION",
    deadline: "15/09/2026",
    updatedAt: "22/08/2026 11:30",
    readiness: 85,
    missing: ["Bổ sung đối sánh mẫu trầm tích chuẩn quốc tế"],
    note: "Cơ quan quyết định yêu cầu chuẩn hóa phương pháp định tuổi bằng đồng vị chì-210.",
    opportunityId: "op08",
    vnOrgId: "org-vn-07",
    ruOrgId: "org-ru-08",
    vnPiId: "exp-vn-11",
    ruPiId: "exp-ru-11",
    endorsementId: "en17",
    reviewAssignmentIds: ["rv10"],
    decisionId: "dc05",
  },
  {
    id: "p21",
    code: "RU-VN-2025-EDDY-21",
    title: "Cấu trúc vi mô và năng lượng xoáy nhiệt đới Tây Thái Bình Dương",
    field: "Hải dương học",
    vnOrg: "IO VAST",
    ruOrg: "FEB RAS",
    vnPi: "TS Đỗ Hùng",
    ruPi: "Dr. Maria Orlova",
    state: "APPROVED",
    deadline: "30/11/2025",
    updatedAt: "19/08/2026 16:10",
    readiness: 100,
    note: "Đã ban hành quyết định chấp thuận, hồ sơ chuyển sang danh mục dự án chính thức.",
    opportunityId: "op10",
    vnOrgId: "org-vn-02",
    ruOrgId: "org-ru-01",
    vnPiId: "exp-vn-08",
    ruPiId: "exp-ru-08",
    endorsementId: "en18",
    decisionId: "dc06",
    projectId: "pr07",
  },
  {
    id: "p22",
    code: "RU-VN-2026-SONAR-22",
    title: "Hệ thống sonar quét sườn đa kênh khảo sát công trình ngầm",
    field: "Robot biển · Thủy âm",
    vnOrg: "HUST",
    ruOrg: "SPbPU",
    vnPi: "TS Đặng Quốc",
    ruPi: "Prof. Alexei Petrov",
    state: "WITHDRAWN",
    deadline: "05/09/2026",
    updatedAt: "20/08/2026 10:40",
    readiness: 50,
    note: "Nhóm nghiên cứu chủ động xin rút hồ sơ để tái cơ cấu thành viên nhóm và nâng cấp thiết bị đo trước đợt sau.",
    opportunityId: "op05",
    vnOrgId: "org-vn-04",
    ruOrgId: "org-ru-04",
    vnPiId: "exp-vn-05",
    ruPiId: "exp-ru-05",
  },
];

export function getProposalById(id: string): DetailedProposal | undefined {
  return DEMO_PROPOSALS.find((item) => item.id === id || item.code === id);
}

export function getProposalsByState(state: ProposalState): DetailedProposal[] {
  return DEMO_PROPOSALS.filter((item) => item.state === state);
}

export function getProposalsByOrg(orgCode: string): DetailedProposal[] {
  return DEMO_PROPOSALS.filter((item) => item.vnOrg === orgCode || item.ruOrg === orgCode || item.vnOrgId === orgCode || item.ruOrgId === orgCode);
}
