import type { ReportItem } from "../demo-v2/types";

export type DetailedReport = ReportItem & {
  submittedAt?: string;
  reviewedAt?: string;
  leadAuthor: string;
  partnerOrg: string;
  summary: string;
  feedback?: string;
  attachmentsCount: number;
};

export const DEMO_REPORTS: DetailedReport[] = [
  {
    id: "rp01",
    projectId: "pr02",
    code: "RU-VN-2026-BIO-08",
    title: "Báo cáo tiến độ giai đoạn 2: Thử nghiệm gia tốc mẫu nano-composite",
    period: "Q2/2026",
    progress: 75,
    state: "PENDING",
    submittedAt: "22/08/2026 14:20",
    leadAuthor: "PGS.TS Lê Thị Mai",
    partnerOrg: "FEB RAS",
    summary: "Đã hoàn thành 500 giờ phun sương muối, xác định độ bền liên kết lớp phủ silica biến tính trên nền hợp kim nhôm biển.",
    attachmentsCount: 3,
  },
  {
    id: "rp02",
    projectId: "pr01",
    code: "RU-VN-2025-OCEAN-03",
    title: "Báo cáo tiến độ giai đoạn 1: Chuẩn hóa cấu trúc dữ liệu phao ngầm",
    period: "H1/2026",
    progress: 48,
    state: "RETURNED",
    submittedAt: "15/08/2026 09:10",
    reviewedAt: "19/08/2026 16:30",
    leadAuthor: "TS Đỗ Hùng",
    partnerOrg: "FEB RAS",
    summary: "Xây dựng bảng từ điển dữ liệu 48 tham số hải dương học đo đạc tự động.",
    feedback: "Cần bổ sung mô tả kiểm chuẩn độ lệch cảm biến đo độ mặn định kỳ theo chuẩn IOC/UNESCO.",
    attachmentsCount: 2,
  },
  {
    id: "rp03",
    projectId: "pr06",
    code: "RU-VN-2026-CLIMATE-11",
    title: "Báo cáo tổng kết và nghiệm thu dự án rủi ro khí hậu đô thị ven biển",
    period: "Final",
    progress: 100,
    state: "APPROVED",
    submittedAt: "05/08/2026 10:00",
    reviewedAt: "10/08/2026 15:00",
    leadAuthor: "TS Nguyễn Thảo",
    partnerOrg: "HSE",
    summary: "Bàn giao trọn bộ atlas số rủi ro ngập lụt ven bờ và 03 bài báo khoa học đã được chấp nhận đăng trên tạp chí uy tín.",
    feedback: "Hội đồng nghiệm thu đánh giá xuất sắc kết quả nghiên cứu và tính ứng dụng thực tiễn cho quy hoạch địa phương.",
    attachmentsCount: 5,
  },
  {
    id: "rp04",
    projectId: "pr04",
    code: "RU-VN-2026-DATA-03",
    title: "Báo cáo xử lý điểm nghẽn cổng kết nối và chứng chỉ dữ liệu",
    period: "M2",
    progress: 31,
    state: "DRAFT",
    leadAuthor: "PGS.TS Phạm Sơn",
    partnerOrg: "FEB RAS",
    summary: "Đang tổng hợp các phương án bảo mật mạng và đề xuất cấu hình tường lửa trung gian.",
    attachmentsCount: 1,
  },
  {
    id: "rp05",
    projectId: "pr07",
    code: "RU-VN-2025-EDDY-21",
    title: "Báo cáo chuyến khảo sát hải dương liên hợp đợt 1 trên tàu Oparin",
    period: "H1/2026",
    progress: 55,
    state: "APPROVED",
    submittedAt: "10/06/2026 11:15",
    reviewedAt: "25/06/2026 14:00",
    leadAuthor: "TS Đỗ Hùng",
    partnerOrg: "FEB RAS",
    summary: "Thu thập thành công chuỗi trắc diện CTD và mẫu sinh vật phù du tại 32 trạm đo ngoài khơi.",
    feedback: "Chuyến khảo sát hoàn thành đúng kế hoạch kỹ thuật đã phê duyệt.",
    attachmentsCount: 4,
  },
  {
    id: "rp06",
    projectId: "pr08",
    code: "RU-VN-2026-ENERGY-09",
    title: "Báo cáo tiến độ mô phỏng động lực học thiết bị thu năng lượng sóng",
    period: "Q2/2026",
    progress: 20,
    state: "OVERDUE",
    leadAuthor: "TS Vũ Linh",
    partnerOrg: "FEFU",
    summary: "Báo cáo quá hạn nộp 5 ngày do nhóm nghiên cứu cần thêm thời gian hiệu chỉnh thuật toán thủy động lực.",
    attachmentsCount: 1,
  },
  {
    id: "rp07",
    projectId: "pr10",
    code: "RU-VN-2026-COAST-06",
    title: "Báo cáo thu thập số liệu trắc đạc địa hình đáy ven bờ dải miền Trung",
    period: "Q2/2026",
    progress: 40,
    state: "SUBMITTED",
    submittedAt: "23/08/2026 08:45",
    leadAuthor: "TS Bùi Thu",
    partnerOrg: "MSU",
    summary: "Hoàn tất đo sâu hồi âm 150 km tuyến khảo sát ven bờ và xử lý số liệu địa hình dạng lưới số độ cao DEM.",
    attachmentsCount: 3,
  },
  {
    id: "rp08",
    projectId: "pr14",
    code: "RU-VN-2026-SEDIMENT-20",
    title: "Báo cáo lấy mẫu lõi trầm tích và mô tả thạch học ban đầu",
    period: "M3",
    progress: 35,
    state: "PENDING",
    submittedAt: "20/08/2026 15:30",
    leadAuthor: "TS Hoàng Long",
    partnerOrg: "GEOKHI RAS",
    summary: "Đã đóng gói và niêm phong 12 mẫu lõi trầm tích chuẩn bị vận chuyển phân tích đồng vị.",
    attachmentsCount: 2,
  },
  {
    id: "rp09",
    projectId: "pr01",
    code: "RU-VN-2025-OCEAN-03",
    title: "Báo cáo khởi động dự án và phân công nhiệm vụ song phương",
    period: "M1",
    progress: 15,
    state: "APPROVED",
    submittedAt: "20/01/2026 10:00",
    reviewedAt: "28/01/2026 16:00",
    leadAuthor: "TS Đỗ Hùng",
    partnerOrg: "FEB RAS",
    summary: "Thống nhất lịch trình làm việc và chỉ định các đầu mối chuyên trách phía Việt Nam và Liên bang Nga.",
    attachmentsCount: 2,
  },
  {
    id: "rp10",
    projectId: "pr02",
    code: "RU-VN-2026-BIO-08",
    title: "Báo cáo thiết lập mẫu chuẩn và tổng hợp màng nano sinh học",
    period: "Q1/2026",
    progress: 35,
    state: "APPROVED",
    submittedAt: "10/05/2026 09:30",
    reviewedAt: "18/05/2026 11:00",
    leadAuthor: "PGS.TS Lê Thị Mai",
    partnerOrg: "FEB RAS",
    summary: "Chế tạo thành công 50 mẫu thử nghiệm đạt độ đồng đều bề mặt theo tiêu chuẩn ASTM.",
    attachmentsCount: 3,
  },
  {
    id: "rp11",
    projectId: "pr10",
    code: "RU-VN-2026-COAST-06",
    title: "Báo cáo khởi động dự án và thiết kế kế hoạch khảo sát dải ven biển",
    period: "M1",
    progress: 15,
    state: "APPROVED",
    submittedAt: "20/06/2026 14:15",
    reviewedAt: "28/06/2026 10:00",
    leadAuthor: "TS Bùi Thu",
    partnerOrg: "MSU",
    summary: "Xác định 12 mặt cắt đo đạc chính và hoàn thành việc xin phép khảo sát thực địa.",
    attachmentsCount: 2,
  },
  {
    id: "rp12",
    projectId: "pr08",
    code: "RU-VN-2026-ENERGY-09",
    title: "Báo cáo khởi động nghiên cứu thiết bị năng lượng sóng phao dao động",
    period: "M1",
    progress: 10,
    state: "APPROVED",
    submittedAt: "15/05/2026 16:00",
    reviewedAt: "22/05/2026 09:00",
    leadAuthor: "TS Vũ Linh",
    partnerOrg: "FEFU",
    summary: "Tổng quan các giải pháp thu năng lượng sóng biển phù hợp vùng ven bờ Việt Nam.",
    attachmentsCount: 2,
  },
  {
    id: "rp13",
    projectId: "pr07",
    code: "RU-VN-2025-EDDY-21",
    title: "Báo cáo lập phương án kỹ thuật chuyến hải trình đo xoáy nhiệt đới",
    period: "M1",
    progress: 20,
    state: "APPROVED",
    submittedAt: "10/03/2026 08:30",
    reviewedAt: "18/03/2026 14:20",
    leadAuthor: "TS Đỗ Hùng",
    partnerOrg: "FEB RAS",
    summary: "Thiết kế mạng lưới trạm quan trắc vệ tinh - tàu khảo sát đồng thời.",
    attachmentsCount: 3,
  },
  {
    id: "rp14",
    projectId: "pr04",
    code: "RU-VN-2026-DATA-03",
    title: "Báo cáo khởi động và thiết kế kiến trúc hệ thống dữ liệu mở",
    period: "M1",
    progress: 15,
    state: "APPROVED",
    submittedAt: "25/04/2026 10:45",
    reviewedAt: "05/05/2026 15:30",
    leadAuthor: "PGS.TS Phạm Sơn",
    partnerOrg: "FEB RAS",
    summary: "Đặc tả kỹ thuật các API chia sẻ dữ liệu và mô hình xác thực OAuth2 song phương.",
    attachmentsCount: 2,
  },
];

export function getReportById(id: string): DetailedReport | undefined {
  return DEMO_REPORTS.find((item) => item.id === id || item.code === id);
}

export function getReportsByProjectId(projectId: string): DetailedReport[] {
  return DEMO_REPORTS.filter((item) => item.projectId === projectId);
}

export function getReportsByState(state: ReportItem["state"]): DetailedReport[] {
  return DEMO_REPORTS.filter((item) => item.state === state);
}
