import type { ReviewAssignment, ReviewState } from "../demo-v2/types";

export type RubricBreakdown = {
  novelty: number;
  methodology: number;
  feasibility: number;
  impact: number;
};

export type DetailedReview = ReviewAssignment & {
  reviewerId?: string;
  conflictReason?: string;
  rubricBreakdown?: RubricBreakdown;
  submittedAt?: string;
};

export const DEMO_REVIEWS: DetailedReview[] = [
  {
    id: "rv01",
    proposalId: "p07",
    code: "RU-VN-2026-BIO-08",
    title: "Độ bền vật liệu sinh học trong điều kiện biển",
    field: "Vật liệu sinh học",
    reviewer: "Chuyên gia #07",
    reviewerId: "exp-vn-12",
    deadline: "30/08/2026",
    state: "IN_REVIEW",
    score: 8.45,
    rubricBreakdown: { novelty: 8.5, methodology: 8.0, feasibility: 8.8, impact: 8.5 },
    comment: "Hồ sơ có luận cứ khoa học rõ, phương pháp thử nghiệm gia tốc chuẩn xác và tính bổ trợ giữa nhóm nghiên cứu Việt Nam – Liên bang Nga rất cao.",
    savedAt: "24/08/2026 17:15",
  },
  {
    id: "rv02",
    proposalId: "p06",
    code: "RU-VN-2026-COAST-06",
    title: "Mô hình số biến động đường bờ khu vực nhiệt đới",
    field: "Địa mạo ven biển",
    reviewer: "Chuyên gia #07",
    reviewerId: "exp-vn-12",
    deadline: "24/08/2026",
    state: "OVERDUE",
    score: 7.9,
    rubricBreakdown: { novelty: 8.0, methodology: 7.5, feasibility: 8.2, impact: 7.9 },
    comment: "Cần hoàn thiện phần hiệu chỉnh mô hình sóng và đối chiếu dữ liệu trắc đạc địa hình thực tế trước khi phê duyệt.",
    savedAt: "23/08/2026 09:30",
  },
  {
    id: "rv03",
    proposalId: "p03",
    code: "RU-VN-2026-MAR-02",
    title: "Giám sát đa dạng sinh học biển bằng dữ liệu ảnh",
    field: "Sinh học biển",
    reviewer: null,
    deadline: "08/09/2026",
    state: "UNASSIGNED",
  },
  {
    id: "rv04",
    proposalId: "p04",
    code: "RU-VN-2026-DATA-03",
    title: "Liên thông dữ liệu quan trắc hải dương VN–RU",
    field: "Dữ liệu khoa học",
    reviewer: "Chuyên gia #12",
    reviewerId: "exp-ru-04",
    deadline: "09/09/2026",
    state: "ASSIGNED",
  },
  {
    id: "rv05",
    proposalId: "p08",
    code: "RU-VN-2026-ENERGY-09",
    title: "Tối ưu vật liệu cho năng lượng sóng quy mô nhỏ",
    field: "Năng lượng biển",
    reviewer: "Chuyên gia #12",
    reviewerId: "exp-ru-07",
    deadline: "20/08/2026",
    state: "SUBMITTED",
    score: 7.2,
    rubricBreakdown: { novelty: 7.5, methodology: 7.0, feasibility: 7.2, impact: 7.1 },
    comment: "Đề nghị nhóm nghiên cứu thu hẹp mục tiêu và bổ sung thử nghiệm thực tế kênh sóng trước khi triển khai quy mô lớn.",
    savedAt: "20/08/2026 14:00",
    submittedAt: "20/08/2026 16:30",
  },
  {
    id: "rv06",
    proposalId: "p10",
    code: "RU-VN-2026-SENSOR-10",
    title: "Cảm biến hóa học bền môi trường nước mặn",
    field: "Cảm biến",
    reviewer: "Chuyên gia #21",
    reviewerId: "exp-ru-09",
    deadline: "12/08/2026",
    state: "SUBMITTED",
    score: 5.8,
    rubricBreakdown: { novelty: 6.5, methodology: 5.5, feasibility: 5.5, impact: 5.7 },
    comment: "Tính khả thi của màng nhạy trong điều kiện muối biển thực tế chưa đủ thuyết phục; chưa có giải pháp chống bám sinh học.",
    savedAt: "12/08/2026 10:20",
    submittedAt: "12/08/2026 11:45",
  },
  {
    id: "rv07",
    proposalId: "p05",
    code: "RU-VN-2026-ROBOT-05",
    title: "Robot tự hành khảo sát vùng nước nông",
    field: "Robot biển",
    reviewer: null,
    deadline: "19/08/2026",
    state: "CANCELLED",
  },
  {
    id: "rv08",
    proposalId: "p01",
    code: "RU-VN-2026-NANO-01",
    title: "Vật liệu nano-composite chịu ăn mòn biển nhiệt đới",
    field: "Vật liệu mới",
    reviewer: "Chuyên gia #21",
    reviewerId: "exp-vn-01",
    deadline: "12/09/2026",
    state: "ASSIGNED",
    conflict: true,
    conflictReason: "Chuyên gia cùng đơn vị chủ trì (VAST) với chủ nhiệm đề xuất.",
  },
  {
    id: "rv09",
    proposalId: "p19",
    code: "RU-VN-2026-QUANTUM-19",
    title: "Từ kế lượng tử quang học thăm dò khoáng sản tầng nông",
    field: "Vật lý lượng tử",
    reviewer: "Chuyên gia #31",
    reviewerId: "exp-ru-02",
    deadline: "25/09/2026",
    state: "ASSIGNED",
  },
  {
    id: "rv10",
    proposalId: "p20",
    code: "RU-VN-2026-SEDIMENT-20",
    title: "Phân tích địa hóa đồng vị trầm tích bồi tụ cửa sông",
    field: "Địa chất biển",
    reviewer: "Chuyên gia #31",
    reviewerId: "exp-ru-11",
    deadline: "15/09/2026",
    state: "SUBMITTED",
    score: 8.5,
    rubricBreakdown: { novelty: 8.5, methodology: 8.8, feasibility: 8.2, impact: 8.5 },
    comment: "Đề tài có giá trị địa chất học cao, kết hợp tốt phương pháp phân tích đồng vị giữa hai viện chuyên ngành.",
    savedAt: "21/08/2026 15:40",
    submittedAt: "21/08/2026 17:00",
  },
  {
    id: "rv11",
    proposalId: "p03",
    code: "RU-VN-2026-MAR-02",
    title: "Giám sát đa dạng sinh học biển bằng dữ liệu ảnh",
    field: "Sinh học biển",
    reviewer: "Chuyên gia #31",
    reviewerId: "exp-ru-03",
    deadline: "10/09/2026",
    state: "IN_REVIEW",
    score: 8.7,
    rubricBreakdown: { novelty: 9.0, methodology: 8.5, feasibility: 8.5, impact: 8.8 },
    comment: "Phương pháp thị giác máy tính cho ảnh sinh vật đáy có tính khả thi và độ chính xác phân loại cao.",
    savedAt: "24/08/2026 16:30",
  },
  {
    id: "rv12",
    proposalId: "p09",
    code: "RU-VN-2025-OCEAN-03",
    title: "Đồng bộ chuỗi quan trắc hải dương học ven bờ",
    field: "Hải dương học",
    reviewer: "Chuyên gia #07",
    reviewerId: "exp-vn-12",
    deadline: "10/12/2025",
    state: "SUBMITTED",
    score: 8.9,
    rubricBreakdown: { novelty: 8.8, methodology: 9.0, feasibility: 9.0, impact: 8.8 },
    comment: "Hồ sơ đáp ứng xuất sắc mọi tiêu chí về hạ tầng, nhân lực và tính cấp thiết song phương.",
    savedAt: "10/12/2025 09:00",
    submittedAt: "10/12/2025 11:30",
  },
  {
    id: "rv13",
    proposalId: "p11",
    code: "RU-VN-2026-CLIMATE-11",
    title: "Đánh giá rủi ro khí hậu cho đô thị ven biển",
    field: "Khí hậu",
    reviewer: "Chuyên gia #12",
    reviewerId: "exp-ru-10",
    deadline: "25/08/2026",
    state: "SUBMITTED",
    score: 8.6,
    rubricBreakdown: { novelty: 8.5, methodology: 8.5, feasibility: 8.8, impact: 8.6 },
    comment: "Mô hình phân tích không gian hoàn chỉnh, đối tượng thử nghiệm rõ ràng.",
    savedAt: "24/08/2026 10:30",
    submittedAt: "24/08/2026 14:00",
  },
  {
    id: "rv14",
    proposalId: "p21",
    code: "RU-VN-2025-EDDY-21",
    title: "Cấu trúc vi mô và năng lượng xoáy nhiệt đới Tây Thái Bình Dương",
    field: "Hải dương học",
    reviewer: "Chuyên gia #21",
    reviewerId: "exp-ru-08",
    deadline: "20/11/2025",
    state: "SUBMITTED",
    score: 9.1,
    rubricBreakdown: { novelty: 9.2, methodology: 9.0, feasibility: 9.2, impact: 9.0 },
    comment: "Ý tưởng xuất sắc, tận dụng tối đa dữ liệu các chuyến khảo sát chung trên biển.",
    savedAt: "18/11/2025 14:15",
    submittedAt: "19/11/2025 09:20",
  },
  {
    id: "rv15",
    proposalId: "p14",
    code: "RU-VN-2026-HYDRO-14",
    title: "Điện cực nano xúc tác sản xuất hydro từ nước biển trực tiếp",
    field: "Năng lượng sạch",
    reviewer: null,
    deadline: "15/11/2026",
    state: "UNASSIGNED",
  },
  {
    id: "rv16",
    proposalId: "p15",
    code: "RU-VN-2026-WAVE-15",
    title: "Thiết bị thu hồi năng lượng sóng dạng phao dao động ven đảo",
    field: "Năng lượng biển",
    reviewer: "Chuyên gia #07",
    reviewerId: "exp-vn-07",
    deadline: "20/10/2026",
    state: "ASSIGNED",
    conflict: true,
    conflictReason: "Đồng tác giả với chủ nhiệm trong công bố gần nhất năm 2025.",
  },
  {
    id: "rv17",
    proposalId: "p17",
    code: "RU-VN-2026-AGRI-17",
    title: "Chỉ thị phân tử sàng lọc giống lúa chịu mặn ven biển",
    field: "Nông nghiệp · Sinh học",
    reviewer: null,
    deadline: "20/12/2026",
    state: "UNASSIGNED",
  },
  {
    id: "rv18",
    proposalId: "p18",
    code: "RU-VN-2026-CORAL-18",
    title: "Nhận dạng tự động biến động rạn san hô bằng AI và camera đáy",
    field: "Sinh học biển · AI",
    reviewer: "Chuyên gia #31",
    reviewerId: "exp-ru-03",
    deadline: "25/08/2026",
    state: "OVERDUE",
    score: 7.8,
    rubricBreakdown: { novelty: 8.2, methodology: 7.5, feasibility: 7.5, impact: 8.0 },
    comment: "Đang chờ tác giả bổ sung giải pháp xử lý ảnh nước đục trước khi hoàn tất chấm điểm.",
    savedAt: "24/08/2026 14:00",
  },
];

export function getReviewById(id: string): DetailedReview | undefined {
  return DEMO_REVIEWS.find((item) => item.id === id || item.code === id);
}

export function getReviewsByProposalId(proposalId: string): DetailedReview[] {
  return DEMO_REVIEWS.filter((item) => item.proposalId === proposalId);
}

export function getReviewsByState(state: ReviewState): DetailedReview[] {
  return DEMO_REVIEWS.filter((item) => item.state === state);
}
