services:
  postgres:
    ports: !reset []

  keycloak:
    ports: !reset []

  auth-service:
    ports: !reset []

  frontend:
    ports: !reset []

  nginx:
    ports: !override
      - "127.0.0.1:8080:80"
