services:
  postgres:
    ports: !reset []

  auth-service:
    environment:
      NODE_ENV: production
    ports: !reset []

  frontend:
    ports: !reset []

  nginx:
    ports: !override
      - "127.0.0.1:8080:80"
