import Link from "next/link";
import type { DiscoveryResult, PublicExpert, PublicPublication } from "../../knowledge/types";

type Props={publications:DiscoveryResult<PublicPublication>;experts:DiscoveryResult<PublicExpert>};
const metrics=["Đối tác đang theo dõi","Công bố đã lưu","Expert matches","2+2 opportunities"];
export default function DashboardView({publications,experts}:Props){return <div className="mx-auto max-w-[1580px] px-4 py-7 sm:px-6 lg:px-8 lg:py-8">
  <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><span className="inline-flex rounded-full border border-slate-200 bg-white px-3 py-2 text-[10px] font-black uppercase text-slate-500">Runtime workspace · real PUBLIC discovery</span><h1 className="mt-4 text-3xl font-black sm:text-4xl">Workspace Nga–Việt</h1><p className="mt-2 text-sm text-slate-600">Identity/context từ Module 01. Publications/Experts PUBLIC từ Module 02.</p></div><Link href="/workspace/knowledge" className="rounded-2xl bg-blue-600 px-4 py-3 text-sm font-black text-white">Khám phá Module 02 →</Link></div>
  <section className="rounded-[28px] bg-[#071831] p-8 text-white"><h2 className="text-3xl font-black sm:text-5xl">Identity rõ ràng. Tri thức liên kết. Hợp tác có đường đi.</h2><div className="mt-6 flex gap-3"><Link href="/workspace/iam" className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-black">Mở IAM workspace</Link><Link href="/workspace/knowledge" className="rounded-xl border border-white/15 px-4 py-3 text-sm font-black">Mở Knowledge workspace</Link></div></section>
  <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(label=><article key={label} className="rounded-[20px] border border-slate-200 bg-white p-5"><span className="text-xs font-bold text-slate-500">{label}</span><strong className="mt-2 block text-xl font-black text-slate-400">Pending</strong><span className="mt-3 inline-flex rounded-full bg-amber-50 px-2 py-1 text-[10px] font-black text-amber-700">No aggregate contract</span></article>)}</div>
  <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-[24px] border border-slate-200 bg-white p-6"><div className="flex justify-between"><h3 className="text-lg font-black">Publications</h3><Link href="/workspace/knowledge" className="text-xs font-black text-blue-600">Xem tất cả →</Link></div>{publications.status==="success"?<div className="mt-3 divide-y">{publications.items.map(p=><div key={p.id} className="py-3"><strong className="text-sm">{p.title}</strong><span className="block text-xs text-slate-500">{p.type} · {p.year} · {p.country}</span></div>)}</div>:<p className="mt-4 text-sm text-rose-700">Publications tạm thời không khả dụng.</p>}</section><section className="rounded-[24px] border border-slate-200 bg-white p-6"><div className="flex justify-between"><h3 className="text-lg font-black">Experts</h3><span className="text-xs font-black text-amber-700">Matching pending</span></div>{experts.status==="success"?<div className="mt-3 grid gap-3">{experts.items.map(e=><div key={e.id} className="rounded-2xl bg-slate-50 p-3"><strong className="text-sm">{e.displayName}</strong><span className="block text-xs text-slate-500">{e.organization.name} · {e.country}</span></div>)}</div>:<p className="mt-4 text-sm text-rose-700">Experts tạm thời không khả dụng.</p>}</section></div>
  <div className="mt-5 flex flex-wrap gap-3"><Link href="/admin/iam" className="rounded-2xl border bg-white p-4 text-sm font-black">Access Administration</Link><Link href="/security" className="rounded-2xl border bg-white p-4 text-sm font-black">Security & Sessions</Link></div>
</div>}
