"use client";

import { useState } from "react";
import { useCurrentUser } from "@/features/auth/server-state";
import { useProject } from "../hooks";

export function ProjectDetail({ id }: { id: string }) {
  const data = useProject(id);
  const { data: user } = useCurrentUser();
  const [memberId, setMemberId] = useState("");
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [outcomeType, setOutcomeType] = useState("");
  const [outcomeRef, setOutcomeRef] = useState("");
  const [reason, setReason] = useState("");
  const run = async (action: Promise<unknown>) => { await action; await data.refetch(); };
  if (data.isLoading) return <p className="p-8" aria-live="polite">Đang tải… / Loading…</p>;
  if (data.isError) return <section className="p-8"><p role="alert">{data.error instanceof Error ? data.error.message : "Request failed"}</p><button type="button" onClick={() => data.refetch()}>Retry</button></section>;
  const project = data.project;
  if (!project) return <p className="p-8">Not found</p>;
  const caps = user?.capabilities ?? [];
  const canUpdate = caps.includes("projects.milestones.update");
  const canSubmit = caps.includes("projects.reports.submit");
  const canApprove = caps.includes("projects.reports.approve");
  return <div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-8">
    <header className="app-panel p-6"><p className="text-xs font-bold uppercase text-blue-600">{project.status}</p><h1 className="mt-2 text-2xl font-bold">{project.title}</h1><p className="mt-2 text-sm text-text-secondary">{project.description}</p><p className="text-xs">Version {project.expectedVersion}</p></header>
    <section className="app-panel p-6"><h2 className="text-lg font-bold">Team</h2><ul className="mt-3 grid gap-2 sm:grid-cols-2">{data.members.map((member) => <li key={member.id} className="rounded-xl border p-3 text-sm"><strong>{member.role}</strong><span className="ml-2 break-all">{member.userId}</span></li>)}</ul>{canApprove && <form className="mt-4 flex flex-wrap gap-2" onSubmit={(event) => { event.preventDefault(); void run(data.addMember({ id, input: { userId: memberId, role: "MEMBER" } })).then(() => setMemberId("")); }}><label className="sr-only" htmlFor="member-id">User ID</label><input id="member-id" required value={memberId} onChange={(event) => setMemberId(event.target.value)} placeholder="User UUID" className="min-w-64 flex-1 rounded-xl border p-3"/><button type="submit" disabled={data.isPending} className="rounded-xl bg-blue-600 px-4 py-2 text-white">Add member</button></form>}</section>
    <section className="app-panel p-6"><h2 className="text-lg font-bold">Milestones & deliverables</h2><div className="mt-4 space-y-3">{project.milestones.map((milestone) => <article key={milestone.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-bold">{milestone.title}</h3><p className="text-sm text-text-secondary">{milestone.description}</p><p className="text-xs">{milestone.status} · {new Date(milestone.dueDate).toLocaleDateString()}</p></div><div className="flex flex-wrap gap-2">{canUpdate && milestone.status !== "APPROVED" && <><button type="button" disabled={data.isPending} onClick={() => run(data.updateMilestone({ id, milestoneId: milestone.id, input: { title: title || milestone.title, expectedVersion: milestone.expectedVersion } }))} className="rounded-lg border px-3 py-2">Update</button><button type="button" disabled={data.isPending} onClick={() => run(data.submitMilestone({ id, milestoneId: milestone.id, input: { expectedVersion: milestone.expectedVersion } }))} className="rounded-lg bg-blue-600 px-3 py-2 text-white">Submit</button></>}{canApprove && milestone.status === "SUBMITTED" && <button type="button" disabled={data.isPending} onClick={() => run(data.reviewMilestone({ id, milestoneId: milestone.id, input: { approved: true, feedback: reason || undefined, expectedVersion: milestone.expectedVersion } }))} className="rounded-lg bg-emerald-600 px-3 py-2 text-white">Approve</button>}</div></div><ul className="mt-2 list-disc pl-5 text-sm">{milestone.deliverables.map((item, index) => <li key={item.id ?? `${item.title}-${index}`}>{item.url ? <a className="text-blue-600 underline" href={item.url}>{item.title}</a> : item.title}</li>)}</ul></article>)}</div>{canUpdate && <form className="mt-4 grid gap-2 sm:grid-cols-3" onSubmit={(event) => { event.preventDefault(); void run(data.createMilestone({ id, input: { title, description: content || undefined, dueDate } })); }}><input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Milestone title" className="rounded-xl border p-3"/><input type="date" required value={dueDate} onChange={(event) => setDueDate(event.target.value)} className="rounded-xl border p-3"/><button type="submit" disabled={data.isPending} className="rounded-xl bg-blue-600 px-4 py-2 text-white">Create milestone</button></form>}</section>
    <section className="app-panel p-6"><h2 className="text-lg font-bold">Progress reports</h2><div className="mt-4 space-y-3">{project.reports.map((report) => <article key={report.id} className="rounded-xl border p-4"><h3 className="font-bold">{report.title}</h3><p className="whitespace-pre-wrap text-sm">{report.content}</p><p className="text-xs">{report.status} · version {report.expectedVersion}</p><div className="mt-2 flex gap-2">{canSubmit && report.status !== "APPROVED" && <><button type="button" disabled={data.isPending} onClick={() => run(data.updateReport({ id, reportId: report.id, input: { content: content || report.content, expectedVersion: report.expectedVersion } }))} className="rounded-lg border px-3 py-2">Update</button><button type="button" disabled={data.isPending} onClick={() => run(data.submitReport({ id, reportId: report.id, input: { expectedVersion: report.expectedVersion } }))} className="rounded-lg bg-blue-600 px-3 py-2 text-white">Submit</button></>}{canApprove && report.status === "SUBMITTED" && <button type="button" disabled={data.isPending} onClick={() => run(data.reviewReport({ id, reportId: report.id, input: { approved: true, feedback: reason || undefined, expectedVersion: report.expectedVersion } }))} className="rounded-lg bg-emerald-600 px-3 py-2 text-white">Approve</button>}</div></article>)}</div>{canSubmit && <form className="mt-4 grid gap-2" onSubmit={(event) => { event.preventDefault(); void run(data.createReport({ id, input: { title, content } })); }}><input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Report title" className="rounded-xl border p-3"/><textarea required value={content} onChange={(event) => setContent(event.target.value)} placeholder="Report content" className="min-h-28 rounded-xl border p-3"/><button type="submit" disabled={data.isPending} className="justify-self-start rounded-xl bg-blue-600 px-4 py-2 text-white">Create report</button></form>}</section>
    <section className="app-panel p-6"><h2 className="text-lg font-bold">Outcomes</h2><ul className="mt-3 space-y-2">{project.outcomes.map((outcome) => <li key={outcome.id} className="rounded-xl border p-3 text-sm"><strong>{outcome.outcomeType}</strong> · {outcome.outcomeRef}</li>)}</ul>{canUpdate && <form className="mt-4 flex flex-wrap gap-2" onSubmit={(event) => { event.preventDefault(); void run(data.addOutcome({ id, input: { outcomeType, outcomeRef } })); }}><input required value={outcomeType} onChange={(event) => setOutcomeType(event.target.value)} placeholder="Outcome type" className="rounded-xl border p-3"/><input required value={outcomeRef} onChange={(event) => setOutcomeRef(event.target.value)} placeholder="Outcome reference" className="min-w-64 flex-1 rounded-xl border p-3"/><button type="submit" disabled={data.isPending} className="rounded-xl bg-blue-600 px-4 py-2 text-white">Add outcome</button></form>}</section>
    {canApprove && project.status === "ACTIVE" && <section className="app-panel space-y-3 p-6"><label className="block text-sm font-semibold">Feedback / termination reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} className="mt-1 block w-full rounded-xl border p-3"/></label><div className="flex gap-2"><button type="button" disabled={data.isPending} onClick={() => run(data.complete({ id, input: { expectedVersion: project.expectedVersion } }))} className="rounded-xl bg-blue-600 px-4 py-2 text-white">Complete project</button><button type="button" disabled={!reason || data.isPending} onClick={() => run(data.terminate({ id, input: { reason, expectedVersion: project.expectedVersion } }))} className="rounded-xl border border-rose-500 px-4 py-2 text-rose-600">Terminate</button></div></section>}
  </div>;
}
