import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const root = new URL("./themes/vnru/login/", import.meta.url);
const properties = await readFile(new URL("theme.properties", root), "utf8");
const css = await readFile(new URL("resources/css/login.css", root), "utf8");
const login = await readFile(new URL("login.ftl", root), "utf8");
const bundles = await Promise.all(["vi", "en", "ru"].map((locale) => readFile(new URL(`messages/messages_${locale}.properties`, root), "utf8")));
const keys = (bundle) => [...bundle.matchAll(/^([^#!\s][^=]*)=/gm)].map((match) => match[1]).sort();
assert.deepEqual(keys(bundles[0]), keys(bundles[1]));
assert.deepEqual(keys(bundles[0]), keys(bundles[2]));
assert.match(properties, /^parent=keycloak\.v2$/m);
assert.match(properties, /^styles=css\/login\.css$/m);
assert.match(css, /--bg:#06142c/);
assert.match(css, /\.vnru-auth-hero/);
assert.match(css, /grid-template-columns:1\.08fr \.92fr/);
assert.match(login, /id="kc-form-login"/);
assert.match(login, /action="\$\{url\.loginAction\}"/);
assert.match(login, /name="username"/);
assert.match(login, /name="password"/);
assert.doesNotMatch(login, /Ghi nhớ đăng nhập|rememberMe/);
assert.doesNotMatch(login, /placehold\.co|\/api\/auth\/login/);
assert.match(login, /vnru-auth-hero/);
assert.match(login, /vnru-network-scene/);
assert.match(login, /net-path hot/);
assert.match(login, /msg\("secureAccess"\)/);
assert.match(login, /msg\("welcomeBack"\)/);
assert.match(login, /vnru-security-note/);
assert.match(login, /class="vnru-google-button"[^>]*disabled/);
assert.ok(login.indexOf("vnru-google-button") > login.indexOf('id="kc-login"'));
assert.doesNotMatch(login, /1k\+|50\+|10\+|prototype|Demo UI/);
assert.match(css, /grid-template-columns:\s*1\.08fr \.92fr/);
assert.match(css, /@keyframes dash/);
assert.match(css, /@keyframes pulse/);
assert.match(css, /prefers-reduced-motion/);
console.log("Keycloak theme smoke: pass");
