import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const root = new URL("./themes/vnru/login/", import.meta.url);
const properties = await readFile(new URL("theme.properties", root), "utf8");
const css = await readFile(new URL("resources/css/login.css", root), "utf8");
const login = await readFile(new URL("login.ftl", root), "utf8");
const script = await readFile(new URL("resources/js/login.js", root), "utf8");
const bundles = await Promise.all(["vi", "en", "ru"].map((locale) => readFile(new URL(`messages/messages_${locale}.properties`, root), "utf8")));
const [vi, en, ru] = bundles;
const keys = (bundle) => [...bundle.matchAll(/^([^#!\s][^=]*)=/gm)].map((match) => match[1]).sort();
assert.deepEqual(keys(bundles[0]), keys(bundles[1]));
assert.deepEqual(keys(bundles[0]), keys(bundles[2]));
assert.match(properties, /^parent=keycloak\.v2$/m);
assert.match(properties, /^styles=css\/login\.css$/m);
assert.match(properties, /^scripts=js\/login\.js$/m);
assert.match(properties, /^locales=vi,en,ru$/m);
assert.doesNotMatch(vi, /Russia-Vietnam|Knowledge|Experts|Portal|Sign in|Invalid username or password/);
assert.match(vi, /^portalLogin=Đăng nhập$/m);
assert.match(en, /^portalLogin=Sign in$/m);
assert.match(ru, /^portalLogin=Войти$/m);
assert.match(en, /^heroTitleAccent=between Vietnam and Russia\.$/m);
assert.match(ru, /^heroTitleAccent=Вьетнама и России\.$/m);
assert.match(css, /--bg:#06142c/);
assert.match(css, /\.vnru-auth-hero/);
assert.match(css, /#login-select-toggle\{/);
assert.match(css, /grid-template-columns:minmax\(0,1\.12fr\) minmax\(420px,\.88fr\)/);
assert.match(login, /id="kc-form-login"/);
assert.match(login, /action="\$\{url\.loginAction\}"/);
assert.match(login, /name="username"/);
assert.match(login, /name="password"/);
assert.doesNotMatch(login, /Ghi nhớ đăng nhập|rememberMe/);
assert.doesNotMatch(login, /placehold\.co|\/api\/auth\/login/);
assert.match(login, /vnru-auth-hero/);
assert.match(login, /vnru-network-scene/);
assert.match(login, /net-path hot/);
assert.match(login, /msg\("secureAccess"\)/);
assert.match(login, /msg\("welcomeBack"\)/);
assert.match(login, /class="vnru-title-accent"/);
assert.match(login, /vnru-security-note/);
assert.match(script, /vnru_locale=\$\{locale\}/);
assert.match(script, /location\.replace\(target\.href\)/);
assert.doesNotMatch(login, /vnru-google-button|googleLogin|comingSoon/);
assert.doesNotMatch(login, /portalLogin\)\} <span|aria-hidden="true">→/);
assert.match(login, /msg\("networkName"\)/);
assert.match(login, /msg\("knowledgeTitle"\)/);
assert.doesNotMatch(login, /1k\+|50\+|10\+|prototype|Demo UI/);
assert.doesNotMatch(css, /border-left:\s*2px/);
assert.doesNotMatch(css, /background-image:\s*linear-gradient/);
assert.match(css, /@keyframes dash/);
assert.match(css, /@keyframes pulse/);
assert.match(css, /@keyframes type-char/);
assert.match(css, /prefers-reduced-motion/);
console.log("Keycloak theme smoke: pass");
